/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ncsa_hdf_hdf5lib_H5_H5_H5L */

#ifndef _Included_ncsa_hdf_hdf5lib_H5_H5L
#define _Included_ncsa_hdf_hdf5lib_H5_H5L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ncsa_hdf_hdf5lib_H5
 * Method:    H5Lget_val
 * Signature: (ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lget_1val
  (JNIEnv *, jclass, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
