/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ncsa_hdf_hdf5lib_H5_H5_H5L */

#ifndef _Included_ncsa_hdf_hdf5lib_H5_H5L
#define _Included_ncsa_hdf_hdf5lib_H5_H5L
#ifdef __cplusplus
extern "C" {
#endif
    
    extern JavaVM *jvm;
    extern jobject visit_callback;   
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lcopy
     * Signature: (ILjava/lang/String;ILjava/lang/String;II)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lcopy
      (JNIEnv *, jclass, jint, jstring, jint, jstring, jint, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lcreate_external
     * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;II)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lcreate_1external
      (JNIEnv *, jclass, jstring, jstring, jint, jstring, jint, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lcreate_hard
     * Signature: (ILjava/lang/String;ILjava/lang/String;II)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lcreate_1hard
      (JNIEnv *, jclass, jint, jstring, jint, jstring, jint, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lcreate_soft
     * Signature: (Ljava/lang/String;ILjava/lang/String;II)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lcreate_1soft
      (JNIEnv *, jclass, jstring, jint, jstring, jint, jint);
  
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Ldelete
     * Signature: (ILjava/lang/String;I)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Ldelete
      (JNIEnv *, jclass, jint, jstring, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Ldelete_by_idx
     * Signature: (ILjava/lang/String;IIJI)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Ldelete_1by_1idx
      (JNIEnv *, jclass, jint, jstring, jint, jint, jlong, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lexists
     * Signature: (ILjava/lang/String;I)Z
     */
    JNIEXPORT jboolean JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lexists
      (JNIEnv *, jclass, jint, jstring, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lget_info
     * Signature: (ILjava/lang/String;I)Lncsa/hdf/hdf5lib/structs/H5L_info_t;
     */
    JNIEXPORT jobject JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lget_1info
      (JNIEnv *, jclass, jint, jstring, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lget_info_by_idx
     * Signature: (ILjava/lang/String;IIJI)Lncsa/hdf/hdf5lib/structs/H5L_info_t;
     */
    JNIEXPORT jobject JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lget_1info_1by_1idx
      (JNIEnv *, jclass, jint, jstring, jint, jint, jlong, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lget_name_by_idx
     * Signature: (ILjava/lang/String;IIJI)Ljava/lang/String;
     */
    JNIEXPORT jobject JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lget_1name_1by_1idx
      (JNIEnv *, jclass, jint, jstring, jint, jint, jlong, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lget_val
     * Signature: (ILjava/lang/String;[Ljava/lang/String;I)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lget_1val
      (JNIEnv *, jclass, jint, jstring, jobjectArray, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lget_val_by_idx
     * Signature: (ILjava/lang/String;IIJ[Ljava/lang/String;I)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lget_1val_1by_1idx
      (JNIEnv *, jclass, jint, jstring, jint, jint, jlong, jobjectArray, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lmove
     * Signature: (ILjava/lang/String;ILjava/lang/String;II)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lmove
      (JNIEnv *, jclass, jint, jstring, jint, jstring, jint, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lvisit
     * Signature: (IIILjava/lang/Object;Ljava/lang/Object;)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lvisit
      (JNIEnv *, jclass, jint, jint, jint, jobject, jobject);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Lvisit_by_name
     * Signature: (ILjava/lang/String;IILjava/lang/Object;Ljava/lang/Object;I)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Lvisit_1by_1name
      (JNIEnv *, jclass, jint, jstring, jint, jint, jobject, jobject, jint);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Literate
     * Signature: (IIIJLjava/lang/Object;Ljava/lang/Object;)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Literate
      (JNIEnv *, jclass, jint, jint, jint, jlong, jobject, jobject);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Literate_by_name
     * Signature: (ILjava/lang/String;IILjava/lang/Object;Ljava/lang/Object;I)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Literate_1by_1name
      (JNIEnv *, jclass, jint, jstring, jint, jint, jlong, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
