/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ncsa_hdf_hdf5lib_H5_H5_H5O */

#ifndef _Included_ncsa_hdf_hdf5lib_H5_H5O
#define _Included_ncsa_hdf_hdf5lib_H5_H5O
#ifdef __cplusplus
extern "C" {
#endif
    
    extern JavaVM *jvm;
    extern jobject visit_callback;   

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    _H5Oopen
     * Signature: (JLjava/lang/String;J)J
     */
    JNIEXPORT jlong JNICALL Java_ncsa_hdf_hdf5lib_H5__1H5Oopen
      (JNIEnv*, jclass, jlong, jstring, jlong);

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    _H5Oclose
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5__1H5Oclose
      (JNIEnv*, jclass, jlong);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Ocopy
     * Signature: (JLjava/lang/String;JLjava/lang/String;JJ)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Ocopy
      (JNIEnv*, jclass, jlong, jstring, jlong, jstring, jlong, jlong);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oget_info
     * Signature: (J)Lncsa/hdf/hdf5lib/structs/H5O_info_t;
     */
    JNIEXPORT jobject JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oget_1info
    (JNIEnv*, jclass, jlong);

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oget_info_by_name
     * Signature: (JLjava/lang/String;J)Lncsa/hdf/hdf5lib/structs/H5O_info_t;
     */
    JNIEXPORT jobject JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oget_1info_1by_1name
    (JNIEnv*, jclass, jlong, jstring, jlong);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oget_info_by_idx
     * Signature: (JLjava/lang/String;IIJJ)Lncsa/hdf/hdf5lib/structs/H5O_info_t;
     */
    JNIEXPORT jobject JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oget_1info_1by_1idx
    (JNIEnv*, jclass, jlong, jstring, jint, jint, jlong, jlong);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Olink
     * Signature: (JJLjava/lang/String;JJ)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Olink
      (JNIEnv*, jclass, jlong, jlong, jstring, jlong, jlong);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Ovisit
     * Signature: (JIILjava/lang/Object;Ljava/lang/Object;)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Ovisit
      (JNIEnv*, jclass, jlong, jint, jint, jobject, jobject);
    
    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Ovisit_by_name
     * Signature: (JLjava/lang/String;IILjava/lang/Object;Ljava/lang/Object;J)I
     */
    JNIEXPORT jint JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Ovisit_1by_1name
      (JNIEnv*, jclass, jlong, jstring, jint, jint, jobject, jobject, jlong);

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oset_comment
     * Signature: (JLjava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oset_1comment
      (JNIEnv*, jclass, jlong, jstring);

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oset_comment_by_name
     * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
     */
    JNIEXPORT void JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oset_1comment_1by_1name
      (JNIEnv*, jclass, jlong, jstring, jstring, jlong);

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oget_comment
     * Signature: (J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oget_1comment
      (JNIEnv*, jclass, jlong);

    /*
     * Class:     ncsa_hdf_hdf5lib_H5
     * Method:    H5Oget_comment_by_name
     * Signature: (JLjava/lang/String;J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_ncsa_hdf_hdf5lib_H5_H5Oget_1comment_1by_1name
      (JNIEnv*, jclass, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
