/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5constant */

#ifndef _Included_hdf_h5_constants_H5constant
#define _Included_hdf_h5_constants_H5constant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5constant_JH5_SZIP_MAX_PIXELS_PER_BLOCK
#define hdf_h5_constants_H5constant_JH5_SZIP_MAX_PIXELS_PER_BLOCK 1000L
#undef hdf_h5_constants_H5constant_JH5_SZIP_NN_OPTION_MASK
#define hdf_h5_constants_H5constant_JH5_SZIP_NN_OPTION_MASK 1010L
#undef hdf_h5_constants_H5constant_JH5_SZIP_EC_OPTION_MASK
#define hdf_h5_constants_H5constant_JH5_SZIP_EC_OPTION_MASK 1020L
#undef hdf_h5_constants_H5constant_JH5_SZIP_ALLOW_K13_OPTION_MASK
#define hdf_h5_constants_H5constant_JH5_SZIP_ALLOW_K13_OPTION_MASK 1021L
#undef hdf_h5_constants_H5constant_JH5_SZIP_CHIP_OPTION_MASK
#define hdf_h5_constants_H5constant_JH5_SZIP_CHIP_OPTION_MASK 1022L
#undef hdf_h5_constants_H5constant_H5_ITER_ERROR
#define hdf_h5_constants_H5constant_H5_ITER_ERROR -1L
#undef hdf_h5_constants_H5constant_H5_ITER_CONT
#define hdf_h5_constants_H5constant_H5_ITER_CONT 0L
#undef hdf_h5_constants_H5constant_H5_ITER_STOP
#define hdf_h5_constants_H5constant_H5_ITER_STOP 1L
/*
 * Class:     hdf_h5_constants_H5constant
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5constant_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
