/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5E */

#ifndef _Included_hdf_h5_H5E
#define _Included_hdf_h5_H5E
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eregister_class
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5E_H5Eregister_1class
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eunregister_class
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Eunregister_1class
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eclose_msg
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Eclose_1msg
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Ecreate_msg
 * Signature: (ILhdf/h5/enums/H5E_TYPE;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5E_H5Ecreate_1msg
  (JNIEnv *, jclass, jint, jobject, jstring);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Ecreate_stack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5E_H5Ecreate_1stack
  (JNIEnv *, jclass);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eget_current_stack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5E_H5Eget_1current_1stack
  (JNIEnv *, jclass);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eclose_stack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Eclose_1stack
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eget_class_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5E_H5Eget_1class_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eset_current_stack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Eset_1current_1stack
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Epop
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Epop
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eprint2
 * Signature: (ILjava/io/File;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Eprint2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eclear2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5E_H5Eclear2
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eauto_is_v2
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5E_H5Eauto_1is_1v2
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eget_msg
 * Signature: (I[Lhdf/h5/enums/H5E_TYPE;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5E_H5Eget_1msg
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     hdf_h5_H5E
 * Method:    H5Eget_num
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5E_H5Eget_1num
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
