/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Fconstant */

#ifndef _Included_hdf_h5_constants_H5Fconstant
#define _Included_hdf_h5_constants_H5Fconstant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_constants_H5Fconstant
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Fconstant_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
