/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Gconstant */

#ifndef _Included_hdf_h5_constants_H5Gconstant
#define _Included_hdf_h5_constants_H5Gconstant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5Gconstant_JH5G_DATASET
#define hdf_h5_constants_H5Gconstant_JH5G_DATASET 2500L
#undef hdf_h5_constants_H5Gconstant_JH5G_GROUP
#define hdf_h5_constants_H5Gconstant_JH5G_GROUP 2510L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK
#define hdf_h5_constants_H5Gconstant_JH5G_LINK 2520L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK_ERROR
#define hdf_h5_constants_H5Gconstant_JH5G_LINK_ERROR 2530L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK_HARD
#define hdf_h5_constants_H5Gconstant_JH5G_LINK_HARD 2540L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK_SOFT
#define hdf_h5_constants_H5Gconstant_JH5G_LINK_SOFT 2550L
#undef hdf_h5_constants_H5Gconstant_JH5G_NLIBTYPES
#define hdf_h5_constants_H5Gconstant_JH5G_NLIBTYPES 2560L
#undef hdf_h5_constants_H5Gconstant_JH5G_NTYPES
#define hdf_h5_constants_H5Gconstant_JH5G_NTYPES 2570L
#undef hdf_h5_constants_H5Gconstant_JH5G_NUSERTYPES
#define hdf_h5_constants_H5Gconstant_JH5G_NUSERTYPES 2580L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_4
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_4 2590L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_5
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_5 2600L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_6
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_6 2610L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_7
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_7 2620L
#undef hdf_h5_constants_H5Gconstant_JH5G_SAME_LOC
#define hdf_h5_constants_H5Gconstant_JH5G_SAME_LOC 2630L
#undef hdf_h5_constants_H5Gconstant_JH5G_TYPE
#define hdf_h5_constants_H5Gconstant_JH5G_TYPE 2640L
#undef hdf_h5_constants_H5Gconstant_JH5G_UNKNOWN
#define hdf_h5_constants_H5Gconstant_JH5G_UNKNOWN 2650L
#undef hdf_h5_constants_H5Gconstant_JH5G_USERTYPE
#define hdf_h5_constants_H5Gconstant_JH5G_USERTYPE 2660L
/*
 * Class:     hdf_h5_constants_H5Gconstant
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Gconstant_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
