/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Iconstant */

#ifndef _Included_hdf_h5_constants_H5Iconstant
#define _Included_hdf_h5_constants_H5Iconstant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5Iconstant_JH5I_ATTR
#define hdf_h5_constants_H5Iconstant_JH5I_ATTR 2670L
#undef hdf_h5_constants_H5Iconstant_JH5I_BADID
#define hdf_h5_constants_H5Iconstant_JH5I_BADID 2680L
#undef hdf_h5_constants_H5Iconstant_JH5I_DATASET
#define hdf_h5_constants_H5Iconstant_JH5I_DATASET 2690L
#undef hdf_h5_constants_H5Iconstant_JH5I_DATASPACE
#define hdf_h5_constants_H5Iconstant_JH5I_DATASPACE 2700L
#undef hdf_h5_constants_H5Iconstant_JH5I_DATATYPE
#define hdf_h5_constants_H5Iconstant_JH5I_DATATYPE 2710L
#undef hdf_h5_constants_H5Iconstant_JH5I_FILE
#define hdf_h5_constants_H5Iconstant_JH5I_FILE 2720L
#undef hdf_h5_constants_H5Iconstant_JH5I_FILE_CLOSING
#define hdf_h5_constants_H5Iconstant_JH5I_FILE_CLOSING 2730L
#undef hdf_h5_constants_H5Iconstant_JH5I_GENPROP_CLS
#define hdf_h5_constants_H5Iconstant_JH5I_GENPROP_CLS 2740L
#undef hdf_h5_constants_H5Iconstant_JH5I_GENPROP_LST
#define hdf_h5_constants_H5Iconstant_JH5I_GENPROP_LST 2750L
#undef hdf_h5_constants_H5Iconstant_JH5I_GROUP
#define hdf_h5_constants_H5Iconstant_JH5I_GROUP 2760L
#undef hdf_h5_constants_H5Iconstant_JH5I_INVALID_HID
#define hdf_h5_constants_H5Iconstant_JH5I_INVALID_HID 2770L
#undef hdf_h5_constants_H5Iconstant_JH5I_NGROUPS
#define hdf_h5_constants_H5Iconstant_JH5I_NGROUPS 2780L
#undef hdf_h5_constants_H5Iconstant_JH5I_REFERENCE
#define hdf_h5_constants_H5Iconstant_JH5I_REFERENCE 2790L
#undef hdf_h5_constants_H5Iconstant_JH5I_TEMPBUF
#define hdf_h5_constants_H5Iconstant_JH5I_TEMPBUF 2800L
#undef hdf_h5_constants_H5Iconstant_JH5I_VFL
#define hdf_h5_constants_H5Iconstant_JH5I_VFL 2810L
/*
 * Class:     hdf_h5_constants_H5Iconstant
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Iconstant_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
