/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5P */

#ifndef _Included_hdf_h5_H5P
#define _Included_hdf_h5_H5P
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_class_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1class_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pcreate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pcreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset
 * Signature: (ILjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset
  (JNIEnv *, jclass, jint, jstring, jbyteArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pexist
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5P_H5Pexist
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_size
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1size
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_nprops
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1nprops
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_class
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1class
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_class_parent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1class_1parent
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5P_H5Pget
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pequal
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5P_H5Pequal
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pisa_class
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5P_H5Pisa_1class
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pcopy_prop
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pcopy_1prop
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Premove
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Premove
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Punregister
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Punregister
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pclose_class
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pclose_1class
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pcopy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pcopy
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_attr_phase_change
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1attr_1phase_1change
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_attr_phase_change
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1attr_1phase_1change
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_attr_creation_order
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1attr_1creation_1order
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_attr_creation_order
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1attr_1creation_1order
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_obj_track_times
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1obj_1track_1times
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_obj_track_times
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5P_H5Pget_1obj_1track_1times
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_version
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1version
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_userblock
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1userblock
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_userblock
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1userblock
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_sizes
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1sizes
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_sizes
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_hdf_h5_H5P_H5Pget_1sizes
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_sym_k
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1sym_1k
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_sym_k
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1sym_1k
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_istore_k
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1istore_1k
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_istore_k
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1istore_1k
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_shared_mesg_nindexes
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1shared_1mesg_1nindexes
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_shared_mesg_nindexes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1shared_1mesg_1nindexes
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_shared_mesg_index
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1shared_1mesg_1index
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_shared_mesg_index
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1shared_1mesg_1index
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_shared_mesg_phase_change
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1shared_1mesg_1phase_1change
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_shared_mesg_phase_change
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1shared_1mesg_1phase_1change
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_alignment
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1alignment
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_alignment
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_hdf_h5_H5P_H5Pget_1alignment
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_driver
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1driver
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_family_offset
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1family_1offset
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_family_offset
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1family_1offset
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_multi_type
 * Signature: (ILhdf/h5/enums/H5FD_MEM;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1multi_1type
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_multi_type
 * Signature: (I)Lhdf/h5/enums/H5FD_MEM;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1multi_1type
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_cache
 * Signature: (IJJD)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pset_1cache
  (JNIEnv *, jclass, jint, jlong, jlong, jdouble);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_cache
 * Signature: (I[I)D
 */
JNIEXPORT jdouble JNICALL Java_hdf_h5_H5P_H5Pget_1cache
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_gc_references
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1gc_1references
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_gc_references
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5P_H5Pget_1gc_1references
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_fclose_degree
 * Signature: (ILhdf/h5/enums/H5F_CLOSE_DEGREE;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1fclose_1degree
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_fclose_degree
 * Signature: (I)Lhdf/h5/enums/H5F_CLOSE_DEGREE;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1fclose_1degree
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_meta_block_size
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1meta_1block_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_meta_block_size
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1meta_1block_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_sieve_buf_size
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1sieve_1buf_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_sieve_buf_size
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1sieve_1buf_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_small_data_block_size
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1small_1data_1block_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_small_data_block_size
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1small_1data_1block_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_libver_bounds
 * Signature: (ILhdf/h5/enums/H5F_LIBVER;Lhdf/h5/enums/H5F_LIBVER;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1libver_1bounds
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_libver_bounds
 * Signature: (I)[Lhdf/h5/enums/H5F_LIBVER;
 */
JNIEXPORT jobjectArray JNICALL Java_hdf_h5_H5P_H5Pget_1libver_1bounds
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_layout
 * Signature: (ILhdf/h5/enums/H5D_LAYOUT;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1layout
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_layout
 * Signature: (I)Lhdf/h5/enums/H5D_LAYOUT;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1layout
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_chunk
 * Signature: (II[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1chunk
  (JNIEnv *, jclass, jint, jint, jlongArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_chunk
 * Signature: (II[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1chunk
  (JNIEnv *, jclass, jint, jint, jlongArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_external
 * Signature: (ILjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1external
  (JNIEnv *, jclass, jint, jstring, jlong, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_external_count
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1external_1count
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_external
 * Signature: (II[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1external
  (JNIEnv *, jclass, jint, jint, jlongArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pmodify_filter
 * Signature: (ILhdf/h5/enums/H5Z_FILTER;IJ[I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pmodify_1filter
  (JNIEnv *, jclass, jint, jobject, jint, jlong, jintArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_filter
 * Signature: (ILhdf/h5/enums/H5Z_FILTER;IJ[I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1filter
  (JNIEnv *, jclass, jint, jobject, jint, jlong, jintArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_nfilters
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1nfilters
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_filter2
 * Signature: (II[I[I[I[Lhdf/h5/enums/H5Z_FILTER;[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1filter2
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray, jobjectArray, jintArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_filter_by_id2
 * Signature: (ILhdf/h5/enums/H5Z_FILTER;[I[J[I[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1filter_1by_1id2
  (JNIEnv *, jclass, jint, jobject, jintArray, jlongArray, jintArray, jintArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pall_filters_avail
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5P_H5Pall_1filters_1avail
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Premove_filter
 * Signature: (ILhdf/h5/enums/H5Z_FILTER;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Premove_1filter
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_deflate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1deflate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_szip
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1szip
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_shuffle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1shuffle
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_nbit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1nbit
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_scaleoffset
 * Signature: (ILhdf/h5/enums/H5Z_SO_SCALE;I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1scaleoffset
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_fletcher32
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1fletcher32
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_fill_value
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1fill_1value
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_fill_value
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5P_H5Pget_1fill_1value
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pfill_value_defined
 * Signature: (I)Lhdf/h5/enums/H5D_FILL_VALUE;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pfill_1value_1defined
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_alloc_time
 * Signature: (ILhdf/h5/enums/H5D_ALLOC_TIME;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1alloc_1time
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_alloc_time
 * Signature: (I)Lhdf/h5/enums/H5D_ALLOC_TIME;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1alloc_1time
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_fill_time
 * Signature: (ILhdf/h5/enums/H5D_FILL_TIME;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1fill_1time
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_fill_time
 * Signature: (I)Lhdf/h5/enums/H5D_FILL_TIME;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1fill_1time
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_chunk_cache
 * Signature: (IJJD)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1chunk_1cache
  (JNIEnv *, jclass, jint, jlong, jlong, jdouble);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_chunk_cache
 * Signature: (I[J)D
 */
JNIEXPORT jdouble JNICALL Java_hdf_h5_H5P_H5Pget_1chunk_1cache
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_data_transform
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1data_1transform
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_data_transform
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1data_1transform
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_buffer
 * Signature: (IJ[B[B)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1buffer
  (JNIEnv *, jclass, jint, jlong, jbyteArray, jbyteArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_buffer
 * Signature: (I[B[B)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1buffer
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_edc_check
 * Signature: (ILhdf/h5/enums/H5Z_EDC;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1edc_1check
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_edc_check
 * Signature: (I)Lhdf/h5/enums/H5Z_EDC;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1edc_1check
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_btree_ratios
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1btree_1ratios
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_btree_ratios
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_hdf_h5_H5P_H5Pget_1btree_1ratios
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_hyper_vector_size
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1hyper_1vector_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_hyper_vector_size
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1hyper_1vector_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_create_intermediate_group
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1create_1intermediate_1group
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_create_intermediate_group
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1create_1intermediate_1group
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_local_heap_size_hint
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1local_1heap_1size_1hint
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_local_heap_size_hint
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1local_1heap_1size_1hint
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_link_phase_change
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1link_1phase_1change
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_link_phase_change
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1link_1phase_1change
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_est_link_info
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1est_1link_1info
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_est_link_info
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_hdf_h5_H5P_H5Pget_1est_1link_1info
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_link_creation_order
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1link_1creation_1order
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_link_creation_order
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1link_1creation_1order
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_char_encoding
 * Signature: (ILhdf/h5/enums/H5T_CSET;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1char_1encoding
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_char_encoding
 * Signature: (I)Lhdf/h5/enums/H5T_CSET;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5P_H5Pget_1char_1encoding
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_nlinks
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1nlinks
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_nlinks
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5P_H5Pget_1nlinks
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_elink_prefix
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1elink_1prefix
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_elink_prefix
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1elink_1prefix
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_elink_fapl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1elink_1fapl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_elink_fapl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1elink_1fapl
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_elink_acc_flags
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1elink_1acc_1flags
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_elink_acc_flags
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1elink_1acc_1flags
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pset_copy_object
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5P_H5Pset_1copy_1object
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_copy_object
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5P_H5Pget_1copy_1object
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_filter1
 * Signature: (II[I[I[I[Lhdf/h5/enums/H5Z_FILTER;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1filter1
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray, jobjectArray);

/*
 * Class:     hdf_h5_H5P
 * Method:    H5Pget_filter_by_id1
 * Signature: (ILhdf/h5/enums/H5Z_FILTER;[I[J[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5P_H5Pget_1filter_1by_1id1
  (JNIEnv *, jclass, jint, jobject, jintArray, jlongArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
