/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Pconstant */

#ifndef _Included_hdf_h5_constants_H5Pconstant
#define _Included_hdf_h5_constants_H5Pconstant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5Pconstant_JH5P_DATASET_CREATE
#define hdf_h5_constants_H5Pconstant_JH5P_DATASET_CREATE 2820L
#undef hdf_h5_constants_H5Pconstant_JH5P_DATASET_CREATE_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_DATASET_CREATE_DEFAULT 2830L
#undef hdf_h5_constants_H5Pconstant_JH5P_DATASET_XFER
#define hdf_h5_constants_H5Pconstant_JH5P_DATASET_XFER 2840L
#undef hdf_h5_constants_H5Pconstant_JH5P_DATASET_XFER_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_DATASET_XFER_DEFAULT 2850L
#undef hdf_h5_constants_H5Pconstant_JH5P_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_DEFAULT 2860L
#undef hdf_h5_constants_H5Pconstant_JH5P_FILE_ACCESS
#define hdf_h5_constants_H5Pconstant_JH5P_FILE_ACCESS 2870L
#undef hdf_h5_constants_H5Pconstant_JH5P_FILE_ACCESS_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_FILE_ACCESS_DEFAULT 2880L
#undef hdf_h5_constants_H5Pconstant_JH5P_FILE_CREATE
#define hdf_h5_constants_H5Pconstant_JH5P_FILE_CREATE 2890L
#undef hdf_h5_constants_H5Pconstant_JH5P_FILE_CREATE_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_FILE_CREATE_DEFAULT 2900L
#undef hdf_h5_constants_H5Pconstant_JH5P_MOUNT
#define hdf_h5_constants_H5Pconstant_JH5P_MOUNT 2910L
#undef hdf_h5_constants_H5Pconstant_JH5P_MOUNT_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_MOUNT_DEFAULT 2920L
#undef hdf_h5_constants_H5Pconstant_JH5P_NO_CLASS
#define hdf_h5_constants_H5Pconstant_JH5P_NO_CLASS 2930L
#undef hdf_h5_constants_H5Pconstant_JH5P_NO_CLASS_DEFAULT
#define hdf_h5_constants_H5Pconstant_JH5P_NO_CLASS_DEFAULT 2940L
/*
 * Class:     hdf_h5_constants_H5Pconstant
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Pconstant_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
