/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5R */

#ifndef _Included_hdf_h5_H5R
#define _Included_hdf_h5_H5R
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5R
 * Method:    H5Rcreate
 * Signature: (ILjava/lang/String;Lhdf/h5/enums/H5R_TYPE;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5R_H5Rcreate
  (JNIEnv *, jclass, jint, jstring, jobject, jint);

/*
 * Class:     hdf_h5_H5R
 * Method:    H5Rdereference
 * Signature: (ILhdf/h5/enums/H5R_TYPE;[B)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5R_H5Rdereference
  (JNIEnv *, jclass, jint, jobject, jbyteArray);

/*
 * Class:     hdf_h5_H5R
 * Method:    H5Rget_region
 * Signature: (ILhdf/h5/enums/H5R_TYPE;[B)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5R_H5Rget_1region
  (JNIEnv *, jclass, jint, jobject, jbyteArray);

/*
 * Class:     hdf_h5_H5R
 * Method:    H5Rget_obj_type2
 * Signature: (ILhdf/h5/enums/H5R_TYPE;[B)Lhdf/h5/enums/H5O_TYPE;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5R_H5Rget_1obj_1type2
  (JNIEnv *, jclass, jint, jobject, jbyteArray);

/*
 * Class:     hdf_h5_H5R
 * Method:    H5Rget_name
 * Signature: (ILhdf/h5/enums/H5R_TYPE;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5R_H5Rget_1name
  (JNIEnv *, jclass, jint, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
