/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Rconstant */

#ifndef _Included_hdf_h5_constants_H5Rconstant
#define _Included_hdf_h5_constants_H5Rconstant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5Rconstant_JH5R_BADTYPE
#define hdf_h5_constants_H5Rconstant_JH5R_BADTYPE 2950L
#undef hdf_h5_constants_H5Rconstant_JH5R_DATASET_REGION
#define hdf_h5_constants_H5Rconstant_JH5R_DATASET_REGION 2960L
#undef hdf_h5_constants_H5Rconstant_JH5R_INTERNAL
#define hdf_h5_constants_H5Rconstant_JH5R_INTERNAL 2970L
#undef hdf_h5_constants_H5Rconstant_JH5R_MAXTYPE
#define hdf_h5_constants_H5Rconstant_JH5R_MAXTYPE 2980L
#undef hdf_h5_constants_H5Rconstant_JH5R_OBJ_REF_BUF_SIZE
#define hdf_h5_constants_H5Rconstant_JH5R_OBJ_REF_BUF_SIZE 2990L
#undef hdf_h5_constants_H5Rconstant_JH5R_OBJECT
#define hdf_h5_constants_H5Rconstant_JH5R_OBJECT 3000L
/*
 * Class:     hdf_h5_constants_H5Rconstant
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Rconstant_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
