/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Rconstant */

#ifndef _Included_hdf_h5_constants_H5Rconstant
#define _Included_hdf_h5_constants_H5Rconstant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5Rconstant_JH5R_BADTYPE
#define hdf_h5_constants_H5Rconstant_JH5R_BADTYPE 10L
#undef hdf_h5_constants_H5Rconstant_JH5R_DATASET_REGION
#define hdf_h5_constants_H5Rconstant_JH5R_DATASET_REGION 20L
#undef hdf_h5_constants_H5Rconstant_JH5R_INTERNAL
#define hdf_h5_constants_H5Rconstant_JH5R_INTERNAL 30L
#undef hdf_h5_constants_H5Rconstant_JH5R_MAXTYPE
#define hdf_h5_constants_H5Rconstant_JH5R_MAXTYPE 40L
#undef hdf_h5_constants_H5Rconstant_JH5R_OBJ_REF_BUF_SIZE
#define hdf_h5_constants_H5Rconstant_JH5R_OBJ_REF_BUF_SIZE 50L
#undef hdf_h5_constants_H5Rconstant_JH5R_OBJECT
#define hdf_h5_constants_H5Rconstant_JH5R_OBJECT 60L
/*
 * Class:     hdf_h5_constants_H5Rconstant
 * Method:    J2C
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Rconstant_J2C
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
