/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5T */

#ifndef _Included_hdf_h5_H5T
#define _Included_hdf_h5_H5T
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tcreate
 * Signature: (Lhdf/h5/enums/H5T_CLASS;J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tcreate
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tcopy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tcopy
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tequal
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5T_H5Tequal
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tlock
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tcommit2
 * Signature: (ILjava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tcommit2
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Topen2
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Topen2
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tcommit_anon
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tcommit_1anon
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_create_plist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1create_1plist
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tcommitted
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5T_H5Tcommitted
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tencode
 * Signature: (I[BJ)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tencode__I_3BJ
  (JNIEnv *, jclass, jint, jbyteArray, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tencode
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5T_H5Tencode__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tdecode
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tdecode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tinsert
 * Signature: (ILjava/lang/String;JI)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tinsert
  (JNIEnv *, jclass, jint, jstring, jlong, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tpack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tpack
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tenum_create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tenum_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tenum_insert
 * Signature: (ILjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tenum_1insert
  (JNIEnv *, jclass, jint, jstring, jbyteArray);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tenum_nameof
 * Signature: (I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5T_H5Tenum_1nameof
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tenum_valueof
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5T_H5Tenum_1valueof
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tvlen_create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tvlen_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tarray_create2
 * Signature: (II[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tarray_1create2
  (JNIEnv *, jclass, jint, jint, jlongArray);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_array_ndims
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1array_1ndims
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_array_dims2
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1array_1dims2
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_tag
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1tag
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_tag
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5T_H5Tget_1tag
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_super
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1super
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_class
 * Signature: (I)Lhdf/h5/enums/H5T_CLASS;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1class
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tdetect_class
 * Signature: (ILhdf/h5/enums/H5T_CLASS;)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5T_H5Tdetect_1class
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_size
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5T_H5Tget_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_order
 * Signature: (I)Lhdf/h5/enums/H5T_ORDER;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1order
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_precision
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5T_H5Tget_1precision
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_offset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1offset
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_pad
 * Signature: (I)[Lhdf/h5/enums/H5T_PAD;
 */
JNIEXPORT jobjectArray JNICALL Java_hdf_h5_H5T_H5Tget_1pad
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_sign
 * Signature: (I)Lhdf/h5/enums/H5T_SGN;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1sign
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_fields
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_hdf_h5_H5T_H5Tget_1fields
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_ebias
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5T_H5Tget_1ebias
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_norm
 * Signature: (I)Lhdf/h5/enums/H5T_NORM;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1norm
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_inpad
 * Signature: (I)Lhdf/h5/enums/H5T_PAD;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1inpad
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_strpad
 * Signature: (I)Lhdf/h5/enums/H5T_STR;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1strpad
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_nmembers
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1nmembers
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_member_name
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5T_H5Tget_1member_1name
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_member_index
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1member_1index
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_member_offset
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5T_H5Tget_1member_1offset
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_member_class
 * Signature: (II)Lhdf/h5/enums/H5T_CLASS;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1member_1class
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_member_type
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5T_H5Tget_1member_1type
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_member_value
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5T_H5Tget_1member_1value
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_cset
 * Signature: (I)Lhdf/h5/enums/H5T_CSET;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1cset
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tis_variable_str
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5T_H5Tis_1variable_1str
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tget_native_type
 * Signature: (ILhdf/h5/enums/H5T_DIR;)Lhdf/h5/enums/H5T_DIR;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5T_H5Tget_1native_1type
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_size
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_order
 * Signature: (ILhdf/h5/enums/H5T_ORDER;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1order
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_precision
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1precision
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_offset
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1offset
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_pad
 * Signature: (ILhdf/h5/enums/H5T_PAD;Lhdf/h5/enums/H5T_PAD;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1pad
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_sign
 * Signature: (ILhdf/h5/enums/H5T_SGN;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1sign
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_fields
 * Signature: (IJJJJJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1fields
  (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_ebias
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1ebias
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_norm
 * Signature: (ILhdf/h5/enums/H5T_NORM;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1norm
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_inpad
 * Signature: (ILhdf/h5/enums/H5T_PAD;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1inpad
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_cset
 * Signature: (ILhdf/h5/enums/H5T_CSET;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1cset
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tset_strpad
 * Signature: (ILhdf/h5/enums/H5T_STR;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tset_1strpad
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tcompiler_conv
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tcompiler_1conv
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5T
 * Method:    H5Tconvert
 * Signature: (IIJ[B[BI)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5T_H5Tconvert
  (JNIEnv *, jclass, jint, jint, jlong, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
