/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5Econstant {
  final private static int JH5E_ALIGNMENT = 1240;
  final private static int JH5E_ALREADYEXISTS = 1250;
  final private static int JH5E_ALREADYINIT = 1260;
  final private static int JH5E_ARGS = 1270;
  final private static int JH5E_ATOM = 1280;
  final private static int JH5E_ATTR = 1290;
  final private static int JH5E_BADATOM = 1300;
  final private static int JH5E_BADFILE = 1310;
  final private static int JH5E_BADGROUP = 1320;
  final private static int JH5E_BADMESG = 1330;
  final private static int JH5E_BADRANGE = 1340;
  final private static int JH5E_BADSELECT = 1350;
  final private static int JH5E_BADSIZE = 1360;
  final private static int JH5E_BADTYPE = 1370;
  final private static int JH5E_BADVALUE = 1380;
  final private static int JH5E_BTREE = 1390;
  final private static int JH5E_CACHE = 1400;
  final private static int JH5E_CALLBACK = 1410;
  final private static int JH5E_CANAPPLY = 1420;
  final private static int JH5E_CANTALLOC = 1430;
  final private static int JH5E_CANTCHANGE = 1440;
  final private static int JH5E_CANTCLIP = 1450;
  final private static int JH5E_CANTCLOSEFILE = 1460;
  final private static int JH5E_CANTCONVERT = 1470;
  final private static int JH5E_CANTCOPY = 1480;
  final private static int JH5E_CANTCOUNT = 1490;
  final private static int JH5E_CANTCREATE = 1500;
  final private static int JH5E_CANTDEC = 1510;
  final private static int JH5E_CANTDECODE = 1520;
  final private static int JH5E_CANTDELETE = 1530;
  final private static int JH5E_CANTENCODE = 1540;
  final private static int JH5E_CANTFLUSH = 1550;
  final private static int JH5E_CANTFREE = 1560;
  final private static int JH5E_CANTGET = 1570;
  final private static int JH5E_CANTINC = 1580;
  final private static int JH5E_CANTINIT = 1590;
  final private static int JH5E_CANTINSERT = 1600;
  final private static int JH5E_CANTLIST = 1610;
  final private static int JH5E_CANTLOAD = 1620;
  final private static int JH5E_CANTLOCK = 1630;
  final private static int JH5E_CANTMAKETREE = 1640;
  final private static int JH5E_CANTNEXT = 1650;
  final private static int JH5E_CANTOPENFILE = 1660;
  final private static int JH5E_CANTOPENOBJ = 1670;
  final private static int JH5E_CANTRECV = 1680;
  final private static int JH5E_CANTREGISTER = 1690;
  final private static int JH5E_CANTRELEASE = 1700;
  final private static int JH5E_CANTSELECT = 1710;
  final private static int JH5E_CANTSENDMDATA = 1720;
  final private static int JH5E_CANTSET = 1730;
  final private static int JH5E_CANTSPLIT = 1740;
  final private static int JH5E_CANTUNLOCK = 1750;
  final private static int JH5E_CLOSEERROR = 1760;
  final private static int JH5E_COMPLEN = 1770;
  final private static int JH5E_CWG = 1780;
  final private static int JH5E_DATASET = 1790;
  final private static int JH5E_DATASPACE = 1800;
  final private static int JH5E_DATATYPE = 1810;
  final private static int JH5E_DUPCLASS = 1820;
  final private static int JH5E_EFL = 1830;
  final private static int JH5E_EXISTS = 1840;
  final private static int JH5E_FCNTL = 1850;
  final private static int JH5E_FILE = 1860;
  final private static int JH5E_FILEEXISTS = 1870;
  final private static int JH5E_FILEOPEN = 1880;
  final private static int JH5E_FPHDF5 = 1890;
  final private static int JH5E_FUNC = 1900;
  final private static int JH5E_HEAP = 1910;
  final private static int JH5E_INTERNAL = 1920;
  final private static int JH5E_IO = 1930;
  final private static int JH5E_LINK = 1940;
  final private static int JH5E_LINKCOUNT = 1950;
  final private static int JH5E_MOUNT = 1960;
  final private static int JH5E_MPI = 1970;
  final private static int JH5E_MPIERRSTR = 1980;
  final private static int JH5E_NOFILTER = 1990;
  final private static int JH5E_NOIDS = 2000;
  final private static int JH5E_NONE_MAJOR = 2010;
  final private static int JH5E_NONE_MINOR = 2020;
  final private static int JH5E_NOSPACE = 2030;
  final private static int JH5E_NOTCACHED = 2040;
  final private static int JH5E_NOTFOUND = 2050;
  final private static int JH5E_NOTHDF5 = 2060;
  final private static int JH5E_OHDR = 2070;
  final private static int JH5E_OVERFLOW = 2080;
  final private static int JH5E_PLINE = 2090;
  final private static int JH5E_PLIST = 2100;
  final private static int JH5E_PROTECT = 2110;
  final private static int JH5E_READERROR = 2120;
  final private static int JH5E_REFERENCE = 2130;
  final private static int JH5E_RESOURCE = 2140;
  final private static int JH5E_RS = 2150;
  final private static int JH5E_SEEKERROR = 2160;
  final private static int JH5E_SETLOCAL = 2170;
  final private static int JH5E_SLINK = 2180;
  final private static int JH5E_STORAGE = 2190;
  final private static int JH5E_SYM = 2200;
  final private static int JH5E_TBBT = 2210;
  final private static int JH5E_TRUNCATED = 2220;
  final private static int JH5E_TST = 2230;
  final private static int JH5E_UNINITIALIZED = 2240;
  final private static int JH5E_UNSUPPORTED = 2250;
  final private static int JH5E_VERSION = 2260;
  final private static int JH5E_VFL = 2270;
  final private static int JH5E_WALK_DOWNWARD = 2280;
  final private static int JH5E_WALK_UPWARD = 2290;
  final private static int JH5E_WRITEERROR = 2300;

  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5E_ALIGNMENT = H5.J2C( JH5E_ALIGNMENT );
  final public static int H5E_ALREADYEXISTS = H5.J2C( JH5E_ALREADYEXISTS );
  final public static int H5E_ALREADYINIT = H5.J2C( JH5E_ALREADYINIT );
  final public static int H5E_ARGS = H5.J2C( JH5E_ARGS );
  final public static int H5E_ATOM = H5.J2C( JH5E_ATOM );
  final public static int H5E_ATTR = H5.J2C( JH5E_ATTR );
  final public static int H5E_BADATOM = H5.J2C( JH5E_BADATOM );
  final public static int H5E_BADFILE = H5.J2C( JH5E_BADFILE );
  final public static int H5E_BADGROUP = H5.J2C( JH5E_BADGROUP );
  final public static int H5E_BADMESG = H5.J2C( JH5E_BADMESG );
  final public static int H5E_BADRANGE = H5.J2C( JH5E_BADRANGE );
  final public static int H5E_BADSELECT = H5.J2C( JH5E_BADSELECT );
  final public static int H5E_BADSIZE = H5.J2C( JH5E_BADSIZE );
  final public static int H5E_BADTYPE = H5.J2C( JH5E_BADTYPE );
  final public static int H5E_BADVALUE = H5.J2C( JH5E_BADVALUE );
  final public static int H5E_BTREE = H5.J2C( JH5E_BTREE );
  final public static int H5E_CACHE = H5.J2C( JH5E_CACHE );
  final public static int H5E_CALLBACK = H5.J2C( JH5E_CALLBACK );
  final public static int H5E_CANAPPLY = H5.J2C( JH5E_CANAPPLY );
  final public static int H5E_CANTALLOC = H5.J2C( JH5E_CANTALLOC );
  final public static int H5E_CANTCHANGE = H5.J2C( JH5E_CANTCHANGE );
  final public static int H5E_CANTCLIP = H5.J2C( JH5E_CANTCLIP );
  final public static int H5E_CANTCLOSEFILE = H5.J2C( JH5E_CANTCLOSEFILE );
  final public static int H5E_CANTCONVERT = H5.J2C( JH5E_CANTCONVERT );
  final public static int H5E_CANTCOPY = H5.J2C( JH5E_CANTCOPY );
  final public static int H5E_CANTCOUNT = H5.J2C( JH5E_CANTCOUNT );
  final public static int H5E_CANTCREATE = H5.J2C( JH5E_CANTCREATE );
  final public static int H5E_CANTDEC = H5.J2C( JH5E_CANTDEC );
  final public static int H5E_CANTDECODE = H5.J2C( JH5E_CANTDECODE );
  final public static int H5E_CANTDELETE = H5.J2C( JH5E_CANTDELETE );
  final public static int H5E_CANTENCODE = H5.J2C( JH5E_CANTENCODE );
  final public static int H5E_CANTFLUSH = H5.J2C( JH5E_CANTFLUSH );
  final public static int H5E_CANTFREE = H5.J2C( JH5E_CANTFREE );
  final public static int H5E_CANTGET = H5.J2C( JH5E_CANTGET );
  final public static int H5E_CANTINC = H5.J2C( JH5E_CANTINC );
  final public static int H5E_CANTINIT = H5.J2C( JH5E_CANTINIT );
  final public static int H5E_CANTINSERT = H5.J2C( JH5E_CANTINSERT );
  final public static int H5E_CANTLIST = H5.J2C( JH5E_CANTLIST );
  final public static int H5E_CANTLOAD = H5.J2C( JH5E_CANTLOAD );
  final public static int H5E_CANTLOCK = H5.J2C( JH5E_CANTLOCK );
  final public static int H5E_CANTMAKETREE = H5.J2C( JH5E_CANTMAKETREE );
  final public static int H5E_CANTNEXT = H5.J2C( JH5E_CANTNEXT );
  final public static int H5E_CANTOPENFILE = H5.J2C( JH5E_CANTOPENFILE );
  final public static int H5E_CANTOPENOBJ = H5.J2C( JH5E_CANTOPENOBJ );
  final public static int H5E_CANTRECV = H5.J2C( JH5E_CANTRECV );
  final public static int H5E_CANTREGISTER = H5.J2C( JH5E_CANTREGISTER );
  final public static int H5E_CANTRELEASE = H5.J2C( JH5E_CANTRELEASE );
  final public static int H5E_CANTSELECT = H5.J2C( JH5E_CANTSELECT );
  final public static int H5E_CANTSENDMDATA = H5.J2C( JH5E_CANTSENDMDATA );
  final public static int H5E_CANTSET = H5.J2C( JH5E_CANTSET );
  final public static int H5E_CANTSPLIT = H5.J2C( JH5E_CANTSPLIT );
  final public static int H5E_CANTUNLOCK = H5.J2C( JH5E_CANTUNLOCK );
  final public static int H5E_CLOSEERROR = H5.J2C( JH5E_CLOSEERROR );
  final public static int H5E_COMPLEN = H5.J2C( JH5E_COMPLEN );
  final public static int H5E_CWG = H5.J2C( JH5E_CWG );
  final public static int H5E_DATASET = H5.J2C( JH5E_DATASET );
  final public static int H5E_DATASPACE = H5.J2C( JH5E_DATASPACE );
  final public static int H5E_DATATYPE = H5.J2C( JH5E_DATATYPE );
  final public static int H5E_DUPCLASS = H5.J2C( JH5E_DUPCLASS );
  final public static int H5E_EFL = H5.J2C( JH5E_EFL );
  final public static int H5E_EXISTS = H5.J2C( JH5E_EXISTS );
  final public static int H5E_FCNTL = H5.J2C( JH5E_FCNTL );
  final public static int H5E_FILE = H5.J2C( JH5E_FILE );
  final public static int H5E_FILEEXISTS = H5.J2C( JH5E_FILEEXISTS );
  final public static int H5E_FILEOPEN = H5.J2C( JH5E_FILEOPEN );
  final public static int H5E_FPHDF5 = H5.J2C( JH5E_FPHDF5 );
  final public static int H5E_FUNC = H5.J2C( JH5E_FUNC );
  final public static int H5E_HEAP = H5.J2C( JH5E_HEAP );
  final public static int H5E_INTERNAL = H5.J2C( JH5E_INTERNAL );
  final public static int H5E_IO = H5.J2C( JH5E_IO );
  final public static int H5E_LINK = H5.J2C( JH5E_LINK );
  final public static int H5E_LINKCOUNT = H5.J2C( JH5E_LINKCOUNT );
  final public static int H5E_MOUNT = H5.J2C( JH5E_MOUNT );
  final public static int H5E_MPI = H5.J2C( JH5E_MPI );
  final public static int H5E_MPIERRSTR = H5.J2C( JH5E_MPIERRSTR );
  final public static int H5E_NOFILTER = H5.J2C( JH5E_NOFILTER );
  final public static int H5E_NOIDS = H5.J2C( JH5E_NOIDS );
  final public static int H5E_NONE_MAJOR = H5.J2C( JH5E_NONE_MAJOR );
  final public static int H5E_NONE_MINOR = H5.J2C( JH5E_NONE_MINOR );
  final public static int H5E_NOSPACE = H5.J2C( JH5E_NOSPACE );
  final public static int H5E_NOTCACHED = H5.J2C( JH5E_NOTCACHED );
  final public static int H5E_NOTFOUND = H5.J2C( JH5E_NOTFOUND );
  final public static int H5E_NOTHDF5 = H5.J2C( JH5E_NOTHDF5 );
  final public static int H5E_OHDR = H5.J2C( JH5E_OHDR );
  final public static int H5E_OVERFLOW = H5.J2C( JH5E_OVERFLOW );
  final public static int H5E_PLINE = H5.J2C( JH5E_PLINE );
  final public static int H5E_PLIST = H5.J2C( JH5E_PLIST );
  final public static int H5E_PROTECT = H5.J2C( JH5E_PROTECT );
  final public static int H5E_READERROR = H5.J2C( JH5E_READERROR );
  final public static int H5E_REFERENCE = H5.J2C( JH5E_REFERENCE );
  final public static int H5E_RESOURCE = H5.J2C( JH5E_RESOURCE );
  final public static int H5E_RS = H5.J2C( JH5E_RS );
  final public static int H5E_SEEKERROR = H5.J2C( JH5E_SEEKERROR );
  final public static int H5E_SETLOCAL = H5.J2C( JH5E_SETLOCAL );
  final public static int H5E_SLINK = H5.J2C( JH5E_SLINK );
  final public static int H5E_STORAGE = H5.J2C( JH5E_STORAGE );
  final public static int H5E_SYM = H5.J2C( JH5E_SYM );
  final public static int H5E_TBBT = H5.J2C( JH5E_TBBT );
  final public static int H5E_TRUNCATED = H5.J2C( JH5E_TRUNCATED );
  final public static int H5E_TST = H5.J2C( JH5E_TST );
  final public static int H5E_UNINITIALIZED = H5.J2C( JH5E_UNINITIALIZED );
  final public static int H5E_UNSUPPORTED = H5.J2C( JH5E_UNSUPPORTED );
  final public static int H5E_VERSION = H5.J2C( JH5E_VERSION );
  final public static int H5E_VFL = H5.J2C( JH5E_VFL );
  final public static int H5E_WALK_DOWNWARD = H5.J2C( JH5E_WALK_DOWNWARD );
  final public static int H5E_WALK_UPWARD = H5.J2C( JH5E_WALK_UPWARD );
  final public static int H5E_WRITEERROR = H5.J2C( JH5E_WRITEERROR );

}
