/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5Fconstant {
  final private static int JH5F_ACC_CREAT = 2310;
  final private static int JH5F_ACC_DEBUG = 2320;
  final private static int JH5F_ACC_EXCL = 2330;
  final private static int JH5F_ACC_RDONLY = 2340;
  final private static int JH5F_ACC_RDWR = 2350;
  final private static int JH5F_ACC_TRUNC = 2360;
  final private static int JH5F_CLOSE_DEFAULT = 2370;
  final private static int JH5F_CLOSE_SEMI = 2380;
  final private static int JH5F_CLOSE_STRONG = 2390;
  final private static int JH5F_CLOSE_WEAK = 2400;
  final private static int JH5F_OBJ_ALL = 2410;
  final private static int JH5F_OBJ_ATTR = 2415;
  final private static int JH5F_OBJ_DATASET = 2420;
  final private static int JH5F_OBJ_DATATYPE = 2430;
  final private static int JH5F_OBJ_FILE = 2440;
  final private static int JH5F_OBJ_GROUP = 2450;
  final private static int JH5F_OBJ_LOCAL = 2455; /* 1.6.5 */
  final private static int JH5F_SCOPE_DOWN = 2460;
  final private static int JH5F_SCOPE_GLOBAL = 2470;
  final private static int JH5F_SCOPE_LOCAL = 2480;
  final private static int JH5F_UNLIMITED = 2490;

  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5F_ACC_CREAT = H5.J2C( JH5F_ACC_CREAT );
  final public static int H5F_ACC_DEBUG = H5.J2C( JH5F_ACC_DEBUG );
  final public static int H5F_ACC_EXCL = H5.J2C( JH5F_ACC_EXCL );
  final public static int H5F_ACC_RDONLY = H5.J2C( JH5F_ACC_RDONLY );
  final public static int H5F_ACC_RDWR = H5.J2C( JH5F_ACC_RDWR );
  final public static int H5F_ACC_TRUNC = H5.J2C( JH5F_ACC_TRUNC );
  final public static int H5F_CLOSE_DEFAULT = H5.J2C( JH5F_CLOSE_DEFAULT );
  final public static int H5F_CLOSE_SEMI = H5.J2C( JH5F_CLOSE_SEMI );
  final public static int H5F_CLOSE_STRONG = H5.J2C( JH5F_CLOSE_STRONG );
  final public static int H5F_CLOSE_WEAK = H5.J2C( JH5F_CLOSE_WEAK );
  final public static int H5F_OBJ_ALL = H5.J2C( JH5F_OBJ_ALL );
  final public static int H5F_OBJ_ATTR = H5.J2C( JH5F_OBJ_ATTR );
  final public static int H5F_OBJ_DATASET = H5.J2C( JH5F_OBJ_DATASET );
  final public static int H5F_OBJ_DATATYPE = H5.J2C( JH5F_OBJ_DATATYPE );
  final public static int H5F_OBJ_FILE = H5.J2C( JH5F_OBJ_FILE );
  final public static int H5F_OBJ_GROUP = H5.J2C( JH5F_OBJ_GROUP );
  final public static int H5F_OBJ_LOCAL = H5.J2C( JH5F_OBJ_LOCAL ); /* 1.6.5 */
  final public static int H5F_SCOPE_DOWN = H5.J2C( JH5F_SCOPE_DOWN );
  final public static int H5F_SCOPE_GLOBAL = H5.J2C( JH5F_SCOPE_GLOBAL );
  final public static int H5F_SCOPE_LOCAL = H5.J2C( JH5F_SCOPE_LOCAL );
  final public static int H5F_UNLIMITED = H5.J2C( JH5F_UNLIMITED );

}
