/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
public class H5Iconstant {
    static { H5.loadH5Lib(); } // make sure the library is available.

    ///////////////////////////////////////////////////////////////////////////
    //           The values are used in the C JNI header file.               //
    //      DO NOT CHANGE THE VALUES UNLESS YOU KNOW WHAT YOU DO !!!         //
    ///////////////////////////////////////////////////////////////////////////

    final private static int JH5I_ATTR = 10 ;
    final private static int JH5I_BADID = 20 ;
    final private static int JH5I_DATASET = 30 ;
    final private static int JH5I_DATASPACE = 40 ;
    final private static int JH5I_DATATYPE = 50 ;
    final private static int JH5I_FILE = 60 ;
    final private static int JH5I_FILE_CLOSING = 70 ;
    final private static int JH5I_GENPROP_CLS = 80 ;
    final private static int JH5I_GENPROP_LST = 90 ;
    final private static int JH5I_GROUP = 100 ;
    final private static int JH5I_INVALID_HID = 110 ;
    final private static int JH5I_NGROUPS = 120 ;
    final private static int JH5I_REFERENCE = 130 ;
    final private static int JH5I_TEMPBUF = 140 ;
    final private static int JH5I_VFL = 150 ;

    ///////////////////////////////////////////////////////////////////////////
    //                Get the HDF5 constants from the library                //
    ///////////////////////////////////////////////////////////////////////////
    final public static int H5I_ATTR = J2C( JH5I_ATTR );
    final public static int H5I_BADID = J2C( JH5I_BADID );
    final public static int H5I_DATASET = J2C( JH5I_DATASET );
    final public static int H5I_DATASPACE = J2C( JH5I_DATASPACE );
    final public static int H5I_DATATYPE = J2C( JH5I_DATATYPE );
    final public static int H5I_FILE = J2C( JH5I_FILE );
    final public static int H5I_FILE_CLOSING = J2C( JH5I_FILE_CLOSING );
    final public static int H5I_GENPROP_CLS = J2C( JH5I_GENPROP_CLS );
    final public static int H5I_GENPROP_LST = J2C( JH5I_GENPROP_LST );
    final public static int H5I_GROUP = J2C( JH5I_GROUP );
    final public static int H5I_INVALID_HID = J2C( JH5I_INVALID_HID );
    final public static int H5I_NGROUPS = J2C( JH5I_NGROUPS );
    final public static int H5I_REFERENCE = J2C( JH5I_REFERENCE );
    final public static int H5I_TEMPBUF = J2C( JH5I_TEMPBUF );
    final public static int H5I_VFL = J2C( JH5I_VFL );

    /**
     *  J2C converts a Java constant to an HDF5 constant determined at runtime
     *
     *  @param java_constant IN: The value of Java constant
     *  
     *  @return the value of an HDF5 constant determined at runtime
     **/
    private  synchronized static native int J2C(int java_constant);  

}
