/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5Iconstant {
  final private static int JH5I_ATTR = 2670;
  final private static int JH5I_BADID = 2680;
  final private static int JH5I_DATASET = 2690;
  final private static int JH5I_DATASPACE = 2700;
  final private static int JH5I_DATATYPE = 2710;
  final private static int JH5I_FILE = 2720;
  final private static int JH5I_FILE_CLOSING = 2730;
  final private static int JH5I_GENPROP_CLS = 2740;
  final private static int JH5I_GENPROP_LST = 2750;
  final private static int JH5I_GROUP = 2760;
  final private static int JH5I_INVALID_HID = 2770;
  final private static int JH5I_NGROUPS = 2780;
  final private static int JH5I_REFERENCE = 2790;
  final private static int JH5I_TEMPBUF = 2800;
  final private static int JH5I_VFL = 2810;

  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5I_ATTR = H5.J2C( JH5I_ATTR );
  final public static int H5I_BADID = H5.J2C( JH5I_BADID );
  final public static int H5I_DATASET = H5.J2C( JH5I_DATASET );
  final public static int H5I_DATASPACE = H5.J2C( JH5I_DATASPACE );
  final public static int H5I_DATATYPE = H5.J2C( JH5I_DATATYPE );
  final public static int H5I_FILE = H5.J2C( JH5I_FILE );
  final public static int H5I_FILE_CLOSING = H5.J2C( JH5I_FILE_CLOSING );
  final public static int H5I_GENPROP_CLS = H5.J2C( JH5I_GENPROP_CLS );
  final public static int H5I_GENPROP_LST = H5.J2C( JH5I_GENPROP_LST );
  final public static int H5I_GROUP = H5.J2C( JH5I_GROUP );
  final public static int H5I_INVALID_HID = H5.J2C( JH5I_INVALID_HID );
  final public static int H5I_NGROUPS = H5.J2C( JH5I_NGROUPS );
  final public static int H5I_REFERENCE = H5.J2C( JH5I_REFERENCE );
  final public static int H5I_TEMPBUF = H5.J2C( JH5I_TEMPBUF );
  final public static int H5I_VFL = H5.J2C( JH5I_VFL );

}
