/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
public class H5Pconstant {
    static { H5.loadH5Lib(); } // make sure the library is available.

    ///////////////////////////////////////////////////////////////////////////
    //           The values are used in the C JNI header file.               //
    //      DO NOT CHANGE THE VALUES UNLESS YOU KNOW WHAT YOU DO !!!         //
    ///////////////////////////////////////////////////////////////////////////

    final private static int JH5P_DATASET_CREATE = 10;
    final private static int JH5P_DATASET_CREATE_DEFAULT = 20;
    final private static int JH5P_DATASET_XFER = 30;
    final private static int JH5P_DATASET_XFER_DEFAULT = 40;
    final private static int JH5P_DEFAULT = 50;
    final private static int JH5P_FILE_ACCESS = 60;
    final private static int JH5P_FILE_ACCESS_DEFAULT = 70;
    final private static int JH5P_FILE_CREATE = 80;
    final private static int JH5P_FILE_CREATE_DEFAULT = 90;
    final private static int JH5P_MOUNT = 100;
    final private static int JH5P_MOUNT_DEFAULT = 110;
    final private static int JH5P_NO_CLASS = 120;
    final private static int JH5P_NO_CLASS_DEFAULT = 130;

    ///////////////////////////////////////////////////////////////////////////
    //                Get the HDF5 constants from the library                //
    ///////////////////////////////////////////////////////////////////////////
    final public static int H5P_DATASET_CREATE = J2C( JH5P_DATASET_CREATE );
    final public static int H5P_DATASET_CREATE_DEFAULT = J2C( JH5P_DATASET_CREATE_DEFAULT );
    final public static int H5P_DATASET_XFER = J2C( JH5P_DATASET_XFER );
    final public static int H5P_DATASET_XFER_DEFAULT = J2C( JH5P_DATASET_XFER_DEFAULT );
    final public static int H5P_DEFAULT = J2C( JH5P_DEFAULT );
    final public static int H5P_FILE_ACCESS = J2C( JH5P_FILE_ACCESS );
    final public static int H5P_FILE_ACCESS_DEFAULT = J2C( JH5P_FILE_ACCESS_DEFAULT );
    final public static int H5P_FILE_CREATE = J2C( JH5P_FILE_CREATE );
    final public static int H5P_FILE_CREATE_DEFAULT = J2C( JH5P_FILE_CREATE_DEFAULT );
    final public static int H5P_MOUNT = J2C( JH5P_MOUNT );
    final public static int H5P_MOUNT_DEFAULT = J2C( JH5P_MOUNT_DEFAULT );
    final public static int H5P_NO_CLASS = J2C( JH5P_NO_CLASS );
    final public static int H5P_NO_CLASS_DEFAULT = J2C( JH5P_NO_CLASS_DEFAULT );

    /**
     *  J2C converts a Java constant to an HDF5 constant determined at runtime
     *
     *  @param java_constant IN: The value of Java constant
     *  
     *  @return the value of an HDF5 constant determined at runtime
     **/
    private  synchronized static native int J2C(int java_constant);  

}
