/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
public class H5Tconstant {
    static { H5.loadH5Lib(); } // make sure the library is available.

    ///////////////////////////////////////////////////////////////////////////
    //           The values are used in the C JNI header file.               //
    //      DO NOT CHANGE THE VALUES UNLESS YOU KNOW WHAT YOU DO !!!         //
    ///////////////////////////////////////////////////////////////////////////

    final private static int JH5T_ALPHA_B16 = 10 ;
    final private static int JH5T_ALPHA_B32 = 20 ;
    final private static int JH5T_ALPHA_B64 = 30 ;
    final private static int JH5T_ALPHA_B8 = 40 ;
    final private static int JH5T_ALPHA_F32 = 50 ;
    final private static int JH5T_ALPHA_F64 = 60 ;
    final private static int JH5T_ALPHA_I16 = 70 ;
    final private static int JH5T_ALPHA_I32 = 80 ;
    final private static int JH5T_ALPHA_I64 = 90 ;
    final private static int JH5T_ALPHA_I8 = 100 ;
    final private static int JH5T_ALPHA_U16 = 110 ;
    final private static int JH5T_ALPHA_U32 = 120 ;
    final private static int JH5T_ALPHA_U64 = 130 ;
    final private static int JH5T_ALPHA_U8 = 140 ;
    final private static int JH5T_ARRAY = 150 ;
    final private static int JH5T_BITFIELD = 160 ;
    final private static int JH5T_BKG_NO = 170 ;
    final private static int JH5T_BKG_YES = 180 ;
    final private static int JH5T_C_S1 = 190 ;
    final private static int JH5T_COMPOUND = 200 ;
    final private static int JH5T_CONV_CONV = 210 ;
    final private static int JH5T_CONV_FREE = 220 ;
    final private static int JH5T_CONV_INIT = 230 ;
    final private static int JH5T_CSET_ASCII = 240 ;
    final private static int JH5T_CSET_ERROR = 250 ;
    final private static int JH5T_CSET_RESERVED_1 = 260 ;
    final private static int JH5T_CSET_RESERVED_10 = 270 ;
    final private static int JH5T_CSET_RESERVED_11 = 280 ;
    final private static int JH5T_CSET_RESERVED_12 = 290 ;
    final private static int JH5T_CSET_RESERVED_13 = 300 ;
    final private static int JH5T_CSET_RESERVED_14 = 310 ;
    final private static int JH5T_CSET_RESERVED_15 = 320 ;
    final private static int JH5T_CSET_RESERVED_2 = 330 ;
    final private static int JH5T_CSET_RESERVED_3 = 340 ;
    final private static int JH5T_CSET_RESERVED_4 = 350 ;
    final private static int JH5T_CSET_RESERVED_5 = 360 ;
    final private static int JH5T_CSET_RESERVED_6 = 370 ;
    final private static int JH5T_CSET_RESERVED_7 = 380 ;
    final private static int JH5T_CSET_RESERVED_8 = 390 ;
    final private static int JH5T_CSET_RESERVED_9 = 400 ;
    final private static int JH5T_DIR_ASCEND = 410 ;
    final private static int JH5T_DIR_DEFAULT = 420 ;
    final private static int JH5T_DIR_DESCEND = 430 ;
    final private static int JH5T_ENUM = 440 ;
    final private static int JH5T_FLOAT = 450 ;
    final private static int JH5T_FORTRAN_S1 = 460 ;
    final private static int JH5T_IEEE_F32BE = 470 ;
    final private static int JH5T_IEEE_F32LE = 480 ;
    final private static int JH5T_IEEE_F64BE = 490 ;
    final private static int JH5T_IEEE_F64LE = 500 ;
    final private static int JH5T_INTEGER = 510 ;
    final private static int JH5T_INTEL_B16 = 520 ;
    final private static int JH5T_INTEL_B32 = 530 ;
    final private static int JH5T_INTEL_B64 = 540 ;
    final private static int JH5T_INTEL_B8 = 550 ;
    final private static int JH5T_INTEL_F32 = 560 ;
    final private static int JH5T_INTEL_F64 = 570 ;
    final private static int JH5T_INTEL_I16 = 580 ;
    final private static int JH5T_INTEL_I32 = 590 ;
    final private static int JH5T_INTEL_I64 = 600 ;
    final private static int JH5T_INTEL_I8 = 610 ;
    final private static int JH5T_INTEL_U16 = 620 ;
    final private static int JH5T_INTEL_U32 = 630 ;
    final private static int JH5T_INTEL_U64 = 640 ;
    final private static int JH5T_INTEL_U8 = 650 ;
    final private static int JH5T_MIPS_B16 = 660 ;
    final private static int JH5T_MIPS_B32 = 670 ;
    final private static int JH5T_MIPS_B64 = 680 ;
    final private static int JH5T_MIPS_B8 = 690 ;
    final private static int JH5T_MIPS_F32 = 700 ;
    final private static int JH5T_MIPS_F64 = 710 ;
    final private static int JH5T_MIPS_I16 = 720 ;
    final private static int JH5T_MIPS_I32 = 730 ;
    final private static int JH5T_MIPS_I64 = 740 ;
    final private static int JH5T_MIPS_I8 = 750 ;
    final private static int JH5T_MIPS_U16 = 760 ;
    final private static int JH5T_MIPS_U32 = 770 ;
    final private static int JH5T_MIPS_U64 = 780 ;
    final private static int JH5T_MIPS_U8 = 790 ;
    final private static int JH5T_NATIVE_B16 = 800 ;
    final private static int JH5T_NATIVE_B32 = 810 ;
    final private static int JH5T_NATIVE_B64 = 820 ;
    final private static int JH5T_NATIVE_B8 = 830 ;
    final private static int JH5T_NATIVE_CHAR = 840 ;
    final private static int JH5T_NATIVE_DOUBLE = 850 ;
    final private static int JH5T_NATIVE_FLOAT = 860 ;
    final private static int JH5T_NATIVE_HADDR = 870 ;
    final private static int JH5T_NATIVE_HBOOL = 880 ;
    final private static int JH5T_NATIVE_HERR = 890 ;
    final private static int JH5T_NATIVE_HSIZE = 900 ;
    final private static int JH5T_NATIVE_HSSIZE = 910 ;
    final private static int JH5T_NATIVE_INT = 920 ;
    final private static int JH5T_NATIVE_INT_FAST16 = 930 ;
    final private static int JH5T_NATIVE_INT_FAST32 = 940 ;
    final private static int JH5T_NATIVE_INT_FAST64 = 950 ;
    final private static int JH5T_NATIVE_INT_FAST8 = 960 ;
    final private static int JH5T_NATIVE_INT_LEAST16 = 970 ;
    final private static int JH5T_NATIVE_INT_LEAST32 = 980 ;
    final private static int JH5T_NATIVE_INT_LEAST64 = 990 ;
    final private static int JH5T_NATIVE_INT_LEAST8 = 1000 ;
    final private static int JH5T_NATIVE_INT16 = 1010 ;
    final private static int JH5T_NATIVE_INT32 = 1020 ;
    final private static int JH5T_NATIVE_INT64 = 1030 ;
    final private static int JH5T_NATIVE_INT8 = 1040 ;
    final private static int JH5T_NATIVE_LDOUBLE = 1050 ;
    final private static int JH5T_NATIVE_LLONG = 1060 ;
    final private static int JH5T_NATIVE_LONG = 1070 ;
    final private static int JH5T_NATIVE_OPAQUE = 1080 ;
    final private static int JH5T_NATIVE_SCHAR = 1090 ;
    final private static int JH5T_NATIVE_SHORT = 1100 ;
    final private static int JH5T_NATIVE_UCHAR = 1110 ;
    final private static int JH5T_NATIVE_UINT = 1120 ;
    final private static int JH5T_NATIVE_UINT_FAST16 = 1130 ;
    final private static int JH5T_NATIVE_UINT_FAST32 = 1140 ;
    final private static int JH5T_NATIVE_UINT_FAST64 = 1150 ;
    final private static int JH5T_NATIVE_UINT_FAST8 = 1160 ;
    final private static int JH5T_NATIVE_UINT_LEAST16 = 1170 ;
    final private static int JH5T_NATIVE_UINT_LEAST32 = 1180 ;
    final private static int JH5T_NATIVE_UINT_LEAST64 = 1190 ;
    final private static int JH5T_NATIVE_UINT_LEAST8 = 1200 ;
    final private static int JH5T_NATIVE_UINT16 = 1210 ;
    final private static int JH5T_NATIVE_UINT32 = 1220 ;
    final private static int JH5T_NATIVE_UINT64 = 1230 ;
    final private static int JH5T_NATIVE_UINT8 = 1240 ;
    final private static int JH5T_NATIVE_ULLONG = 1250 ;
    final private static int JH5T_NATIVE_ULONG = 1260 ;
    final private static int JH5T_NATIVE_USHORT = 1270 ;
    final private static int JH5T_NCLASSES = 1280 ;
    final private static int JH5T_NO_CLASS = 1290 ;
    final private static int JH5T_NORM_ERROR = 1300 ;
    final private static int JH5T_NORM_IMPLIED = 1310 ;
    final private static int JH5T_NORM_MSBSET = 1320 ;
    final private static int JH5T_NORM_NONE = 1330 ;
    final private static int JH5T_NPAD = 1340 ;
    final private static int JH5T_NSGN = 1350 ;
    final private static int JH5T_OPAQUE = 1360 ;
    final private static int JH5T_OPAQUE_TAG_MAX = 1370 ; /* 1.6.5 */
    final private static int JH5T_ORDER_BE = 1380 ;
    final private static int JH5T_ORDER_ERROR = 1390 ;
    final private static int JH5T_ORDER_LE = 1400 ;
    final private static int JH5T_ORDER_NONE = 1410 ;
    final private static int JH5T_ORDER_VAX = 1420 ;
    final private static int JH5T_PAD_BACKGROUND = 1430 ;
    final private static int JH5T_PAD_ERROR = 1440 ;
    final private static int JH5T_PAD_ONE = 1450 ;
    final private static int JH5T_PAD_ZERO = 1460 ;
    final private static int JH5T_PERS_DONTCARE = 1470 ;
    final private static int JH5T_PERS_HARD = 1480 ;
    final private static int JH5T_PERS_SOFT = 1490 ;
    final private static int JH5T_REFERENCE = 1500 ;
    final private static int JH5T_SGN_2 = 1510 ;
    final private static int JH5T_SGN_ERROR = 1520 ;
    final private static int JH5T_SGN_NONE = 1530 ;
    final private static int JH5T_STD_B16BE = 1540 ;
    final private static int JH5T_STD_B16LE = 1550 ;
    final private static int JH5T_STD_B32BE = 1560 ;
    final private static int JH5T_STD_B32LE = 1570 ;
    final private static int JH5T_STD_B64BE = 1580 ;
    final private static int JH5T_STD_B64LE = 1590 ;
    final private static int JH5T_STD_B8BE = 1600 ;
    final private static int JH5T_STD_B8LE = 1610 ;
    final private static int JH5T_STD_I16BE = 1620 ;
    final private static int JH5T_STD_I16LE = 1630 ;
    final private static int JH5T_STD_I32BE = 1640 ;
    final private static int JH5T_STD_I32LE = 1650 ;
    final private static int JH5T_STD_I64BE = 1660 ;
    final private static int JH5T_STD_I64LE = 1670 ;
    final private static int JH5T_STD_I8BE = 1680 ;
    final private static int JH5T_STD_I8LE = 1690 ;
    final private static int JH5T_STD_REF_DSETREG = 1700 ;
    final private static int JH5T_STD_REF_OBJ = 1710 ;
    final private static int JH5T_STD_U16BE = 1720 ;
    final private static int JH5T_STD_U16LE = 1730 ;
    final private static int JH5T_STD_U32BE = 1740 ;
    final private static int JH5T_STD_U32LE = 1750 ;
    final private static int JH5T_STD_U64BE = 1760 ;
    final private static int JH5T_STD_U64LE = 1770 ;
    final private static int JH5T_STD_U8BE = 1780 ;
    final private static int JH5T_STD_U8LE = 1790 ;
    final private static int JH5T_STR_ERROR = 1800 ;
    final private static int JH5T_STR_NULLPAD = 1810 ;
    final private static int JH5T_STR_NULLTERM = 1820 ;
    final private static int JH5T_STR_RESERVED_10 = 1830 ;
    final private static int JH5T_STR_RESERVED_11 = 1840 ;
    final private static int JH5T_STR_RESERVED_12 = 1850 ;
    final private static int JH5T_STR_RESERVED_13 = 1860 ;
    final private static int JH5T_STR_RESERVED_14 = 1870 ;
    final private static int JH5T_STR_RESERVED_15 = 1880 ;
    final private static int JH5T_STR_RESERVED_3 = 1890 ;
    final private static int JH5T_STR_RESERVED_4 = 1900 ;
    final private static int JH5T_STR_RESERVED_5 = 1910 ;
    final private static int JH5T_STR_RESERVED_6 = 1920 ;
    final private static int JH5T_STR_RESERVED_7 = 1930 ;
    final private static int JH5T_STR_RESERVED_8 = 1940 ;
    final private static int JH5T_STR_RESERVED_9 = 1950 ;
    final private static int JH5T_STR_SPACEPAD = 1960 ;
    final private static int JH5T_STRING = 1970 ;
    final private static int JH5T_TIME = 1980 ;
    final private static int JH5T_UNIX_D32BE = 1990 ;
    final private static int JH5T_UNIX_D32LE = 2000 ;
    final private static int JH5T_UNIX_D64BE = 2010 ;
    final private static int JH5T_UNIX_D64LE = 2020 ;
    final private static int JH5T_VARIABLE = 2030 ;
    final private static int JH5T_VLEN = 2040 ;

    ///////////////////////////////////////////////////////////////////////////
    //                Get the HDF5 constants from the library                //
    ///////////////////////////////////////////////////////////////////////////
    final public static int H5T_ALPHA_B16 = J2C( JH5T_ALPHA_B16 );
    final public static int H5T_ALPHA_B32 = J2C( JH5T_ALPHA_B32 );
    final public static int H5T_ALPHA_B64 = J2C( JH5T_ALPHA_B64 );
    final public static int H5T_ALPHA_B8 = J2C( JH5T_ALPHA_B8 );
    final public static int H5T_ALPHA_F32 = J2C( JH5T_ALPHA_F32 );
    final public static int H5T_ALPHA_F64 = J2C( JH5T_ALPHA_F64 );
    final public static int H5T_ALPHA_I16 = J2C( JH5T_ALPHA_I16 );
    final public static int H5T_ALPHA_I32 = J2C( JH5T_ALPHA_I32 );
    final public static int H5T_ALPHA_I64 = J2C( JH5T_ALPHA_I64 );
    final public static int H5T_ALPHA_I8 = J2C( JH5T_ALPHA_I8 );
    final public static int H5T_ALPHA_U16 = J2C( JH5T_ALPHA_U16 );
    final public static int H5T_ALPHA_U32 = J2C( JH5T_ALPHA_U32 );
    final public static int H5T_ALPHA_U64 = J2C( JH5T_ALPHA_U64 );
    final public static int H5T_ALPHA_U8 = J2C( JH5T_ALPHA_U8 );
    final public static int H5T_ARRAY = J2C( JH5T_ARRAY );
    final public static int H5T_BITFIELD = J2C( JH5T_BITFIELD );
    final public static int H5T_BKG_NO = J2C( JH5T_BKG_NO );
    final public static int H5T_BKG_YES = J2C( JH5T_BKG_YES );
    final public static int H5T_C_S1 = J2C( JH5T_C_S1 );
    final public static int H5T_COMPOUND = J2C( JH5T_COMPOUND );
    final public static int H5T_CONV_CONV = J2C( JH5T_CONV_CONV );
    final public static int H5T_CONV_FREE = J2C( JH5T_CONV_FREE );
    final public static int H5T_CONV_INIT = J2C( JH5T_CONV_INIT );
    final public static int H5T_CSET_ASCII = J2C( JH5T_CSET_ASCII );
    final public static int H5T_CSET_ERROR = J2C( JH5T_CSET_ERROR );
    final public static int H5T_CSET_RESERVED_1 = J2C( JH5T_CSET_RESERVED_1 );
    final public static int H5T_CSET_RESERVED_10 = J2C( JH5T_CSET_RESERVED_10 );
    final public static int H5T_CSET_RESERVED_11 = J2C( JH5T_CSET_RESERVED_11 );
    final public static int H5T_CSET_RESERVED_12 = J2C( JH5T_CSET_RESERVED_12 );
    final public static int H5T_CSET_RESERVED_13 = J2C( JH5T_CSET_RESERVED_13 );
    final public static int H5T_CSET_RESERVED_14 = J2C( JH5T_CSET_RESERVED_14 );
    final public static int H5T_CSET_RESERVED_15 = J2C( JH5T_CSET_RESERVED_15 );
    final public static int H5T_CSET_RESERVED_2 = J2C( JH5T_CSET_RESERVED_2 );
    final public static int H5T_CSET_RESERVED_3 = J2C( JH5T_CSET_RESERVED_3 );
    final public static int H5T_CSET_RESERVED_4 = J2C( JH5T_CSET_RESERVED_4 );
    final public static int H5T_CSET_RESERVED_5 = J2C( JH5T_CSET_RESERVED_5 );
    final public static int H5T_CSET_RESERVED_6 = J2C( JH5T_CSET_RESERVED_6 );
    final public static int H5T_CSET_RESERVED_7 = J2C( JH5T_CSET_RESERVED_7 );
    final public static int H5T_CSET_RESERVED_8 = J2C( JH5T_CSET_RESERVED_8 );
    final public static int H5T_CSET_RESERVED_9 = J2C( JH5T_CSET_RESERVED_9 );
    final public static int H5T_DIR_ASCEND = J2C( JH5T_DIR_ASCEND );
    final public static int H5T_DIR_DEFAULT = J2C( JH5T_DIR_DEFAULT );
    final public static int H5T_DIR_DESCEND = J2C( JH5T_DIR_DESCEND );
    final public static int H5T_ENUM = J2C( JH5T_ENUM );
    final public static int H5T_FLOAT = J2C( JH5T_FLOAT );
    final public static int H5T_FORTRAN_S1 = J2C( JH5T_FORTRAN_S1 );
    final public static int H5T_IEEE_F32BE = J2C( JH5T_IEEE_F32BE );
    final public static int H5T_IEEE_F32LE = J2C( JH5T_IEEE_F32LE );
    final public static int H5T_IEEE_F64BE = J2C( JH5T_IEEE_F64BE );
    final public static int H5T_IEEE_F64LE = J2C( JH5T_IEEE_F64LE );
    final public static int H5T_INTEGER = J2C( JH5T_INTEGER );
    final public static int H5T_INTEL_B16 = J2C( JH5T_INTEL_B16 );
    final public static int H5T_INTEL_B32 = J2C( JH5T_INTEL_B32 );
    final public static int H5T_INTEL_B64 = J2C( JH5T_INTEL_B64 );
    final public static int H5T_INTEL_B8 = J2C( JH5T_INTEL_B8 );
    final public static int H5T_INTEL_F32 = J2C( JH5T_INTEL_F32 );
    final public static int H5T_INTEL_F64 = J2C( JH5T_INTEL_F64 );
    final public static int H5T_INTEL_I16 = J2C( JH5T_INTEL_I16 );
    final public static int H5T_INTEL_I32 = J2C( JH5T_INTEL_I32 );
    final public static int H5T_INTEL_I64 = J2C( JH5T_INTEL_I64 );
    final public static int H5T_INTEL_I8 = J2C( JH5T_INTEL_I8 );
    final public static int H5T_INTEL_U16 = J2C( JH5T_INTEL_U16 );
    final public static int H5T_INTEL_U32 = J2C( JH5T_INTEL_U32 );
    final public static int H5T_INTEL_U64 = J2C( JH5T_INTEL_U64 );
    final public static int H5T_INTEL_U8 = J2C( JH5T_INTEL_U8 );
    final public static int H5T_MIPS_B16 = J2C( JH5T_MIPS_B16 );
    final public static int H5T_MIPS_B32 = J2C( JH5T_MIPS_B32 );
    final public static int H5T_MIPS_B64 = J2C( JH5T_MIPS_B64 );
    final public static int H5T_MIPS_B8 = J2C( JH5T_MIPS_B8 );
    final public static int H5T_MIPS_F32 = J2C( JH5T_MIPS_F32 );
    final public static int H5T_MIPS_F64 = J2C( JH5T_MIPS_F64 );
    final public static int H5T_MIPS_I16 = J2C( JH5T_MIPS_I16 );
    final public static int H5T_MIPS_I32 = J2C( JH5T_MIPS_I32 );
    final public static int H5T_MIPS_I64 = J2C( JH5T_MIPS_I64 );
    final public static int H5T_MIPS_I8 = J2C( JH5T_MIPS_I8 );
    final public static int H5T_MIPS_U16 = J2C( JH5T_MIPS_U16 );
    final public static int H5T_MIPS_U32 = J2C( JH5T_MIPS_U32 );
    final public static int H5T_MIPS_U64 = J2C( JH5T_MIPS_U64 );
    final public static int H5T_MIPS_U8 = J2C( JH5T_MIPS_U8 );
    final public static int H5T_NATIVE_B16 = J2C( JH5T_NATIVE_B16 );
    final public static int H5T_NATIVE_B32 = J2C( JH5T_NATIVE_B32 );
    final public static int H5T_NATIVE_B64 = J2C( JH5T_NATIVE_B64 );
    final public static int H5T_NATIVE_B8 = J2C( JH5T_NATIVE_B8 );
    final public static int H5T_NATIVE_CHAR = J2C( JH5T_NATIVE_CHAR );
    final public static int H5T_NATIVE_DOUBLE = J2C( JH5T_NATIVE_DOUBLE );
    final public static int H5T_NATIVE_FLOAT = J2C( JH5T_NATIVE_FLOAT );
    final public static int H5T_NATIVE_HADDR = J2C( JH5T_NATIVE_HADDR );
    final public static int H5T_NATIVE_HBOOL = J2C( JH5T_NATIVE_HBOOL );
    final public static int H5T_NATIVE_HERR = J2C( JH5T_NATIVE_HERR );
    final public static int H5T_NATIVE_HSIZE = J2C( JH5T_NATIVE_HSIZE );
    final public static int H5T_NATIVE_HSSIZE = J2C( JH5T_NATIVE_HSSIZE );
    final public static int H5T_NATIVE_INT = J2C( JH5T_NATIVE_INT );
    final public static int H5T_NATIVE_INT_FAST16 = J2C( JH5T_NATIVE_INT_FAST16 );
    final public static int H5T_NATIVE_INT_FAST32 = J2C( JH5T_NATIVE_INT_FAST32 );
    final public static int H5T_NATIVE_INT_FAST64 = J2C( JH5T_NATIVE_INT_FAST64 );
    final public static int H5T_NATIVE_INT_FAST8 = J2C( JH5T_NATIVE_INT_FAST8 );
    final public static int H5T_NATIVE_INT_LEAST16 = J2C( JH5T_NATIVE_INT_LEAST16 );
    final public static int H5T_NATIVE_INT_LEAST32 = J2C( JH5T_NATIVE_INT_LEAST32 );
    final public static int H5T_NATIVE_INT_LEAST64 = J2C( JH5T_NATIVE_INT_LEAST64 );
    final public static int H5T_NATIVE_INT_LEAST8 = J2C( JH5T_NATIVE_INT_LEAST8 );
    final public static int H5T_NATIVE_INT16 = J2C( JH5T_NATIVE_INT16 );
    final public static int H5T_NATIVE_INT32 = J2C( JH5T_NATIVE_INT32 );
    final public static int H5T_NATIVE_INT64 = J2C( JH5T_NATIVE_INT64 );
    final public static int H5T_NATIVE_INT8 = J2C( JH5T_NATIVE_INT8 );
    final public static int H5T_NATIVE_LDOUBLE = J2C( JH5T_NATIVE_LDOUBLE );
    final public static int H5T_NATIVE_LLONG = J2C( JH5T_NATIVE_LLONG );
    final public static int H5T_NATIVE_LONG = J2C( JH5T_NATIVE_LONG );
    final public static int H5T_NATIVE_OPAQUE = J2C( JH5T_NATIVE_OPAQUE );
    final public static int H5T_NATIVE_SCHAR = J2C( JH5T_NATIVE_SCHAR );
    final public static int H5T_NATIVE_SHORT = J2C( JH5T_NATIVE_SHORT );
    final public static int H5T_NATIVE_UCHAR = J2C( JH5T_NATIVE_UCHAR );
    final public static int H5T_NATIVE_UINT = J2C( JH5T_NATIVE_UINT );
    final public static int H5T_NATIVE_UINT_FAST16 = J2C( JH5T_NATIVE_UINT_FAST16 );
    final public static int H5T_NATIVE_UINT_FAST32 = J2C( JH5T_NATIVE_UINT_FAST32 );
    final public static int H5T_NATIVE_UINT_FAST64 = J2C( JH5T_NATIVE_UINT_FAST64 );
    final public static int H5T_NATIVE_UINT_FAST8 = J2C( JH5T_NATIVE_UINT_FAST8 );
    final public static int H5T_NATIVE_UINT_LEAST16 = J2C( JH5T_NATIVE_UINT_LEAST16 );
    final public static int H5T_NATIVE_UINT_LEAST32 = J2C( JH5T_NATIVE_UINT_LEAST32 );
    final public static int H5T_NATIVE_UINT_LEAST64 = J2C( JH5T_NATIVE_UINT_LEAST64 );
    final public static int H5T_NATIVE_UINT_LEAST8 = J2C( JH5T_NATIVE_UINT_LEAST8 );
    final public static int H5T_NATIVE_UINT16 = J2C( JH5T_NATIVE_UINT16 );
    final public static int H5T_NATIVE_UINT32 = J2C( JH5T_NATIVE_UINT32 );
    final public static int H5T_NATIVE_UINT64 = J2C( JH5T_NATIVE_UINT64 );
    final public static int H5T_NATIVE_UINT8 = J2C( JH5T_NATIVE_UINT8 );
    final public static int H5T_NATIVE_ULLONG = J2C( JH5T_NATIVE_ULLONG );
    final public static int H5T_NATIVE_ULONG = J2C( JH5T_NATIVE_ULONG );
    final public static int H5T_NATIVE_USHORT = J2C( JH5T_NATIVE_USHORT );
    final public static int H5T_NCLASSES = J2C( JH5T_NCLASSES );
    final public static int H5T_NO_CLASS = J2C( JH5T_NO_CLASS );
    final public static int H5T_NORM_ERROR = J2C( JH5T_NORM_ERROR );
    final public static int H5T_NORM_IMPLIED = J2C( JH5T_NORM_IMPLIED );
    final public static int H5T_NORM_MSBSET = J2C( JH5T_NORM_MSBSET );
    final public static int H5T_NORM_NONE = J2C( JH5T_NORM_NONE );
    final public static int H5T_NPAD = J2C( JH5T_NPAD );
    final public static int H5T_NSGN = J2C( JH5T_NSGN );
    final public static int H5T_OPAQUE = J2C( JH5T_OPAQUE );
    final public static int H5T_OPAQUE_TAG_MAX  = J2C( JH5T_OPAQUE_TAG_MAX  ); /* 1.6.5 */
    final public static int H5T_ORDER_BE = J2C( JH5T_ORDER_BE );
    final public static int H5T_ORDER_ERROR = J2C( JH5T_ORDER_ERROR );
    final public static int H5T_ORDER_LE = J2C( JH5T_ORDER_LE );
    final public static int H5T_ORDER_NONE = J2C( JH5T_ORDER_NONE );
    final public static int H5T_ORDER_VAX = J2C( JH5T_ORDER_VAX );
    final public static int H5T_PAD_BACKGROUND = J2C( JH5T_PAD_BACKGROUND );
    final public static int H5T_PAD_ERROR = J2C( JH5T_PAD_ERROR );
    final public static int H5T_PAD_ONE = J2C( JH5T_PAD_ONE );
    final public static int H5T_PAD_ZERO = J2C( JH5T_PAD_ZERO );
    final public static int H5T_PERS_DONTCARE = J2C( JH5T_PERS_DONTCARE );
    final public static int H5T_PERS_HARD = J2C( JH5T_PERS_HARD );
    final public static int H5T_PERS_SOFT = J2C( JH5T_PERS_SOFT );
    final public static int H5T_REFERENCE = J2C( JH5T_REFERENCE );
    final public static int H5T_SGN_2 = J2C( JH5T_SGN_2 );
    final public static int H5T_SGN_ERROR = J2C( JH5T_SGN_ERROR );
    final public static int H5T_SGN_NONE = J2C( JH5T_SGN_NONE );
    final public static int H5T_STD_B16BE = J2C( JH5T_STD_B16BE );
    final public static int H5T_STD_B16LE = J2C( JH5T_STD_B16LE );
    final public static int H5T_STD_B32BE = J2C( JH5T_STD_B32BE );
    final public static int H5T_STD_B32LE = J2C( JH5T_STD_B32LE );
    final public static int H5T_STD_B64BE = J2C( JH5T_STD_B64BE );
    final public static int H5T_STD_B64LE = J2C( JH5T_STD_B64LE );
    final public static int H5T_STD_B8BE = J2C( JH5T_STD_B8BE );
    final public static int H5T_STD_B8LE = J2C( JH5T_STD_B8LE );
    final public static int H5T_STD_I16BE = J2C( JH5T_STD_I16BE );
    final public static int H5T_STD_I16LE = J2C( JH5T_STD_I16LE );
    final public static int H5T_STD_I32BE = J2C( JH5T_STD_I32BE );
    final public static int H5T_STD_I32LE = J2C( JH5T_STD_I32LE );
    final public static int H5T_STD_I64BE = J2C( JH5T_STD_I64BE );
    final public static int H5T_STD_I64LE = J2C( JH5T_STD_I64LE );
    final public static int H5T_STD_I8BE = J2C( JH5T_STD_I8BE );
    final public static int H5T_STD_I8LE = J2C( JH5T_STD_I8LE );
    final public static int H5T_STD_REF_DSETREG = J2C( JH5T_STD_REF_DSETREG );
    final public static int H5T_STD_REF_OBJ = J2C( JH5T_STD_REF_OBJ );
    final public static int H5T_STD_U16BE = J2C( JH5T_STD_U16BE );
    final public static int H5T_STD_U16LE = J2C( JH5T_STD_U16LE );
    final public static int H5T_STD_U32BE = J2C( JH5T_STD_U32BE );
    final public static int H5T_STD_U32LE = J2C( JH5T_STD_U32LE );
    final public static int H5T_STD_U64BE = J2C( JH5T_STD_U64BE );
    final public static int H5T_STD_U64LE = J2C( JH5T_STD_U64LE );
    final public static int H5T_STD_U8BE = J2C( JH5T_STD_U8BE );
    final public static int H5T_STD_U8LE = J2C( JH5T_STD_U8LE );
    final public static int H5T_STR_ERROR = J2C( JH5T_STR_ERROR );
    final public static int H5T_STR_NULLPAD = J2C( JH5T_STR_NULLPAD );
    final public static int H5T_STR_NULLTERM = J2C( JH5T_STR_NULLTERM );
    final public static int H5T_STR_RESERVED_10 = J2C( JH5T_STR_RESERVED_10 );
    final public static int H5T_STR_RESERVED_11 = J2C( JH5T_STR_RESERVED_11 );
    final public static int H5T_STR_RESERVED_12 = J2C( JH5T_STR_RESERVED_12 );
    final public static int H5T_STR_RESERVED_13 = J2C( JH5T_STR_RESERVED_13 );
    final public static int H5T_STR_RESERVED_14 = J2C( JH5T_STR_RESERVED_14 );
    final public static int H5T_STR_RESERVED_15 = J2C( JH5T_STR_RESERVED_15 );
    final public static int H5T_STR_RESERVED_3 = J2C( JH5T_STR_RESERVED_3 );
    final public static int H5T_STR_RESERVED_4 = J2C( JH5T_STR_RESERVED_4 );
    final public static int H5T_STR_RESERVED_5 = J2C( JH5T_STR_RESERVED_5 );
    final public static int H5T_STR_RESERVED_6 = J2C( JH5T_STR_RESERVED_6 );
    final public static int H5T_STR_RESERVED_7 = J2C( JH5T_STR_RESERVED_7 );
    final public static int H5T_STR_RESERVED_8 = J2C( JH5T_STR_RESERVED_8 );
    final public static int H5T_STR_RESERVED_9 = J2C( JH5T_STR_RESERVED_9 );
    final public static int H5T_STR_SPACEPAD = J2C( JH5T_STR_SPACEPAD );
    final public static int H5T_STRING = J2C( JH5T_STRING );
    final public static int H5T_TIME = J2C( JH5T_TIME );
    final public static int H5T_UNIX_D32BE = J2C( JH5T_UNIX_D32BE );
    final public static int H5T_UNIX_D32LE = J2C( JH5T_UNIX_D32LE );
    final public static int H5T_UNIX_D64BE = J2C( JH5T_UNIX_D64BE );
    final public static int H5T_UNIX_D64LE = J2C( JH5T_UNIX_D64LE );
    final public static int H5T_VARIABLE = J2C( JH5T_VARIABLE );     // Rosetta Biosoftware 
    final public static int H5T_VLEN = J2C( JH5T_VLEN );

    /**
     *  J2C converts a Java constant to an HDF5 constant determined at runtime
     *
     *  @param java_constant IN: The value of Java constant
     *  
     *  @return the value of an HDF5 constant determined at runtime
     **/
    private  synchronized static native int J2C(int java_constant);
}
