# Generated automatically from Makefile.in by configure.
#/****************************************************************************
# * NCSA HDF                                                                 *
# * National Comptational Science Alliance                                   *
# * University of Illinois at Urbana-Champaign                               *
# * 605 E. Springfield, Champaign IL 61820                                   *
# *                                                                          *
# * For conditions of distribution and use, see the accompanying             *
# * java-hdf5/COPYING file.                                                  *
# *                                                                          *
# ****************************************************************************/


all:
	cd hdflib; \
	$(MAKE) ; 
	cd hdf5lib; \
	$(MAKE) ; 
	cd h4toh5lib; \
	$(MAKE) 

hdflib:
	cd hdflib; \
	$(MAKE) ; 

hdf5lib:
	cd hdf5lib; \
	$(MAKE) ; 

h4to5lib:
	cd h4to5lib; \
	$(MAKE) ; 

clean:
	cd h4toh5lib; $(MAKE) clean;
	cd hdflib; $(MAKE) clean;
	cd hdf5lib; $(MAKE) clean;

clean-hdflib:
	cd hdflib; \
	$(MAKE) clean ; 

clean-hdf5lib:
	cd hdf5lib; \
	$(MAKE) clean ; 

clean-h4toh5lib:
	cd h4toh5lib; \
	$(MAKE) clean ; 
