#!/bin/sh
set -x


INSTDIR=/afs/.ncsa.uiuc.edu/projects/hdf/java/java8/xcao/java/macosx

JAVAINC=/System/Library/Frameworks/JavaVM.framework/Headers
JAVALIB=/System/Library/Frameworks/JavaVM.framework/Libraries

HDF4=/afs/.ncsa.uiuc.edu/packages/hdf/4.2r0-macosx
HDF5=/afs/.ncsa.uiuc.edu/projects/hdf/java/java9/xcao/5-1.6.3-macosx_NoEnc
SZIP=/afs/ncsa.uiuc.edu/projects/hdf/packages/szip_noencoder/Darwin_7.4
GZIP=/afs/ncsa.uiuc.edu/projects/hdf/java/java8/xcao/zlib-1.1.4-macosx
JPEG=/afs/ncsa.uiuc.edu/projects/hdf/packages/jpeg/MacOSX
export CC=/usr/bin/cc

./configure --prefix=$INSTDIR --with-jdk=$JAVAINC,$JAVALIB \
-build=powerpc-apple \
--with-hdf5=$HDF5/include,$HDF5/lib \
--without-hdf4 \
--without-h4toh5 \
--with-libsz=$SZIP/include,$SZIP/lib \
--with-libz=$GZIP/include,$GZIP/lib \
--with-libjpeg=$JPEG/include,$JPEG/lib \
--with-jdkclasses=/System/Library/Frameworks/JavaVM.framework/Classes \
--with-javabin=/System/Library/Frameworks/JavaVM.framework/Commands

