#!/bin/sh
set -x

INSTDIR=/afs/.ncsa.uiuc.edu/projects/hdf/java/java8/xcao/java/linux

JAVAINC=/opt/jdk1.4.1/include
JAVALIB=/opt/jdk1.4.1/jre/lib

HDF4=/afs/ncsa.uiuc.edu/packages/hdf/4.2r0-linux32gcc3.3.2
HDF5=/afs/.ncsa.uiuc.edu/projects/hdf/java/java9/xcao/5-1.6.3-linux_NoEnc
SZIP=/afs/ncsa.uiuc.edu/projects/hdf/packages/szip_noencoder/Linux2.4
GZIP=/afs/ncsa.uiuc.edu/projects/hdf/packages/zlib/Linux2.4
JPEG=/afs/ncsa.uiuc.edu/projects/hdf/java/java10/mcgrath/verbena/JPEG

export CC=/afs/ncsa/projects/hdf/packages/gcc-3.3.2/Linux_2.4/bin/gcc

./configure --prefix=$INSTDIR --with-jdk=$JAVAINC,$JAVALIB \
--with-hdf5=$HDF5/include,$HDF5/lib \
--with-hdf4=$HDF4/include,$HDF4/lib \
--with-libsz=$SZIP/include,$SZIP/lib \
--with-libz=$GZIP/include,$GZIP/lib \
--with-libjpeg=$JPEG/include,$JPEG/lib
 
