/*****************************************************************************
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of the HDF Java Products distribution.                  *
 * The full copyright notice, including terms governing use, modification,   *
 * and redistribution, is contained in the files COPYING and Copyright.html. *
 * COPYING can be found at the root of the source code distribution tree.    *
 * Or, see http://hdfgroup.org/products/hdf-java/doc/Copyright.html.         *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 ****************************************************************************/

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5constant {
  final private static int JH5_SZIP_MAX_PIXELS_PER_BLOCK = 1000;
  final private static int JH5_SZIP_NN_OPTION_MASK = 1010;
  final private static int JH5_SZIP_EC_OPTION_MASK = 1020;
  final private static int JH5_SZIP_ALLOW_K13_OPTION_MASK = 1021;
  final private static int JH5_SZIP_CHIP_OPTION_MASK = 1022;
  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5_SZIP_MAX_PIXELS_PER_BLOCK = H5.J2C( JH5_SZIP_MAX_PIXELS_PER_BLOCK );
  final public static int H5_SZIP_NN_OPTION_MASK = H5.J2C( JH5_SZIP_NN_OPTION_MASK );
  final public static int H5_SZIP_EC_OPTION_MASK = H5.J2C( JH5_SZIP_EC_OPTION_MASK );
  final public static int H5_SZIP_ALLOW_K13_OPTION_MASK = H5.J2C( JH5_SZIP_ALLOW_K13_OPTION_MASK );
  final public static int H5_SZIP_CHIP_OPTION_MASK = H5.J2C( JH5_SZIP_CHIP_OPTION_MASK );

}
