/*****************************************************************************
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of the HDF Java Products distribution.                  *
 * The full copyright notice, including terms governing use, modification,   *
 * and redistribution, is contained in the files COPYING and Copyright.html. *
 * COPYING can be found at the root of the source code distribution tree.    *
 * Or, see http://hdfgroup.org/products/hdf-java/doc/Copyright.html.         *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 ****************************************************************************/

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5Dconstant {
  final private static int JH5D_ALLOC_TIME_DEFAULT = 1030;
  final private static int JH5D_ALLOC_TIME_EARLY = 1040;
  final private static int JH5D_ALLOC_TIME_ERROR = 1050;
  final private static int JH5D_ALLOC_TIME_INCR = 1060;
  final private static int JH5D_ALLOC_TIME_LATE = 1070;
  final private static int JH5D_CHUNKED = 1080;
  final private static int JH5D_COMPACT = 1090;
  final private static int JH5D_CONTIGUOUS = 1100;
  final private static int JH5D_FILL_TIME_ALLOC = 1110;
  final private static int JH5D_FILL_TIME_ERROR = 1120;
  final private static int JH5D_FILL_TIME_NEVER = 1130;
  final private static int JH5D_FILL_VALUE_DEFAULT = 1140;
  final private static int JH5D_FILL_VALUE_ERROR = 1150;
  final private static int JH5D_FILL_VALUE_UNDEFINED = 1160;
  final private static int JH5D_FILL_VALUE_USER_DEFINED = 1170;
  final private static int JH5D_LAYOUT_ERROR = 1180;
  final private static int JH5D_NLAYOUTS = 1190;
  final private static int JH5D_SPACE_STATUS_ALLOCATED = 1200;
  final private static int JH5D_SPACE_STATUS_ERROR = 1210;
  final private static int JH5D_SPACE_STATUS_NOT_ALLOCATED = 1220;
  final private static int JH5D_SPACE_STATUS_PART_ALLOCATED = 1230;

  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5D_ALLOC_TIME_DEFAULT = H5.J2C( JH5D_ALLOC_TIME_DEFAULT );
  final public static int H5D_ALLOC_TIME_EARLY = H5.J2C( JH5D_ALLOC_TIME_EARLY );
  final public static int H5D_ALLOC_TIME_ERROR = H5.J2C( JH5D_ALLOC_TIME_ERROR );
  final public static int H5D_ALLOC_TIME_INCR = H5.J2C( JH5D_ALLOC_TIME_INCR );
  final public static int H5D_ALLOC_TIME_LATE = H5.J2C( JH5D_ALLOC_TIME_LATE );
  final public static int H5D_CHUNKED = H5.J2C( JH5D_CHUNKED );
  final public static int H5D_COMPACT = H5.J2C( JH5D_COMPACT );
  final public static int H5D_CONTIGUOUS = H5.J2C( JH5D_CONTIGUOUS );
  final public static int H5D_FILL_TIME_ALLOC = H5.J2C( JH5D_FILL_TIME_ALLOC );
  final public static int H5D_FILL_TIME_ERROR = H5.J2C( JH5D_FILL_TIME_ERROR );
  final public static int H5D_FILL_TIME_NEVER = H5.J2C( JH5D_FILL_TIME_NEVER );
  final public static int H5D_FILL_VALUE_DEFAULT = H5.J2C( JH5D_FILL_VALUE_DEFAULT );
  final public static int H5D_FILL_VALUE_ERROR = H5.J2C( JH5D_FILL_VALUE_ERROR );
  final public static int H5D_FILL_VALUE_UNDEFINED = H5.J2C( JH5D_FILL_VALUE_UNDEFINED );
  final public static int H5D_FILL_VALUE_USER_DEFINED = H5.J2C( JH5D_FILL_VALUE_USER_DEFINED );
  final public static int H5D_LAYOUT_ERROR = H5.J2C( JH5D_LAYOUT_ERROR );
  final public static int H5D_NLAYOUTS = H5.J2C( JH5D_NLAYOUTS );
  final public static int H5D_SPACE_STATUS_ALLOCATED = H5.J2C( JH5D_SPACE_STATUS_ALLOCATED );
  final public static int H5D_SPACE_STATUS_ERROR = H5.J2C( JH5D_SPACE_STATUS_ERROR );
  final public static int H5D_SPACE_STATUS_NOT_ALLOCATED = H5.J2C( JH5D_SPACE_STATUS_NOT_ALLOCATED );
  final public static int H5D_SPACE_STATUS_PART_ALLOCATED = H5.J2C( JH5D_SPACE_STATUS_PART_ALLOCATED );

}
