/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
public class H5Fconstant {
    ///////////////////////////////////////////////////////////////////////////
    //           The values are used in the C JNI header file.               //
    //      DO NOT CHANGE THE VALUES UNLESS YOU KNOW WHAT YOU DO !!!         //
    ///////////////////////////////////////////////////////////////////////////

    final private static int JH5F_ACC_CREAT = 10 ;
    final private static int JH5F_ACC_DEBUG = 20 ;
    final private static int JH5F_ACC_EXCL = 30 ;
    final private static int JH5F_ACC_RDONLY = 40 ;
    final private static int JH5F_ACC_RDWR = 50 ;
    final private static int JH5F_ACC_TRUNC = 60 ;
    final private static int JH5F_ACC_DEFAULT = 70 ;
    final private static int JH5F_CLOSE_DEFAULT = 80 ;
    final private static int JH5F_CLOSE_SEMI = 90 ;
    final private static int JH5F_CLOSE_STRONG = 100 ;
    final private static int JH5F_CLOSE_WEAK = 110 ;
    final private static int JH5F_OBJ_ALL = 120 ;
    final private static int JH5F_OBJ_ATTR = 130 ;
    final private static int JH5F_OBJ_DATASET = 140 ;
    final private static int JH5F_OBJ_DATATYPE = 150 ;
    final private static int JH5F_OBJ_FILE = 160 ;
    final private static int JH5F_OBJ_GROUP = 170 ;
    final private static int JH5F_OBJ_LOCAL = 180 ;
    final private static int JH5F_SCOPE_DOWN = 190 ;
    final private static int JH5F_SCOPE_GLOBAL = 200 ;
    final private static int JH5F_SCOPE_LOCAL = 210 ;
    final private static int JH5F_UNLIMITED = 220 ;


    ///////////////////////////////////////////////////////////////////////////
    //                Get the HDF5 constants from the library                //
    ///////////////////////////////////////////////////////////////////////////
    final public static int H5F_ACC_CREAT = J2C( JH5F_ACC_CREAT );
    final public static int H5F_ACC_DEBUG = J2C( JH5F_ACC_DEBUG );
    final public static int H5F_ACC_EXCL = J2C( JH5F_ACC_EXCL );
    final public static int H5F_ACC_RDONLY = J2C( JH5F_ACC_RDONLY );
    final public static int H5F_ACC_RDWR = J2C( JH5F_ACC_RDWR );
    final public static int H5F_ACC_TRUNC = J2C( JH5F_ACC_TRUNC );
    final public static int H5F_ACC_DEFAULT = J2C( JH5F_ACC_DEFAULT );
    final public static int H5F_CLOSE_DEFAULT = J2C( JH5F_CLOSE_DEFAULT );
    final public static int H5F_CLOSE_SEMI = J2C( JH5F_CLOSE_SEMI );
    final public static int H5F_CLOSE_STRONG = J2C( JH5F_CLOSE_STRONG );
    final public static int H5F_CLOSE_WEAK = J2C( JH5F_CLOSE_WEAK );
    final public static int H5F_OBJ_ALL = J2C( JH5F_OBJ_ALL );
    final public static int H5F_OBJ_ATTR = J2C( JH5F_OBJ_ATTR );
    final public static int H5F_OBJ_DATASET = J2C( JH5F_OBJ_DATASET );
    final public static int H5F_OBJ_DATATYPE = J2C( JH5F_OBJ_DATATYPE );
    final public static int H5F_OBJ_FILE = J2C( JH5F_OBJ_FILE );
    final public static int H5F_OBJ_GROUP = J2C( JH5F_OBJ_GROUP );
    final public static int H5F_OBJ_LOCAL = J2C( JH5F_OBJ_LOCAL ); /* 1.6.5 */
    final public static int H5F_SCOPE_DOWN = J2C( JH5F_SCOPE_DOWN );
    final public static int H5F_SCOPE_GLOBAL = J2C( JH5F_SCOPE_GLOBAL );
    final public static int H5F_SCOPE_LOCAL = J2C( JH5F_SCOPE_LOCAL );
    final public static int H5F_UNLIMITED = J2C( JH5F_UNLIMITED );

    /**
     *  J2C converts a Java constant to an HDF5 constant determined at runtime
     *
     *  @param java_constant IN: The value of Java constant
     *  
     *  @return the value of an HDF5 constant determined at runtime
     **/
    public synchronized static native int J2C(int java_constant);
}
