/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5Gconstant {
  final private static int JH5G_DATASET = 2500;
  final private static int JH5G_GROUP = 2510;
  final private static int JH5G_LINK = 2520;
  final private static int JH5G_LINK_ERROR = 2530;
  final private static int JH5G_LINK_HARD = 2540;
  final private static int JH5G_LINK_SOFT = 2550;
  final private static int JH5G_NLIBTYPES = 2560;
  final private static int JH5G_NTYPES = 2570;
  final private static int JH5G_NUSERTYPES = 2580;
  final private static int JH5G_RESERVED_4 = 2590;
  final private static int JH5G_RESERVED_5 = 2600;
  final private static int JH5G_RESERVED_6 = 2610;
  final private static int JH5G_RESERVED_7 = 2620;
  final private static int JH5G_SAME_LOC = 2630;
  final private static int JH5G_TYPE = 2640;
  final private static int JH5G_UNKNOWN = 2650;
  final private static int JH5G_USERTYPE = 2660;

  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5G_DATASET = H5.J2C( JH5G_DATASET );
  final public static int H5G_GROUP = H5.J2C( JH5G_GROUP );
  final public static int H5G_LINK = H5.J2C( JH5G_LINK );
  final public static int H5G_LINK_ERROR = H5.J2C( JH5G_LINK_ERROR );
  final public static int H5G_LINK_HARD = H5.J2C( JH5G_LINK_HARD );
  final public static int H5G_LINK_SOFT = H5.J2C( JH5G_LINK_SOFT );
  final public static int H5G_NLIBTYPES = H5.J2C( JH5G_NLIBTYPES );
  final public static int H5G_NTYPES = H5.J2C( JH5G_NTYPES );
  final public static int H5G_NUSERTYPES = H5.J2C( JH5G_NUSERTYPES );
  final public static int H5G_RESERVED_4 = H5.J2C( JH5G_RESERVED_4 );
  final public static int H5G_RESERVED_5 = H5.J2C( JH5G_RESERVED_5 );
  final public static int H5G_RESERVED_6 = H5.J2C( JH5G_RESERVED_6 );
  final public static int H5G_RESERVED_7 = H5.J2C( JH5G_RESERVED_7 );
  final public static int H5G_SAME_LOC = H5.J2C( JH5G_SAME_LOC );
  final public static int H5G_TYPE = H5.J2C( JH5G_TYPE );
  final public static int H5G_UNKNOWN = H5.J2C( JH5G_UNKNOWN );
  final public static int H5G_USERTYPE = H5.J2C( JH5G_USERTYPE );
  
  /**
   * Get the value of a constant variable from the library. Some of the
   * library constants are defined at run-time. Using get() will make sure
   * the constants are correct. 
   */
  private synchronized static native int get(String constantName);
  

}
