/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
public class H5Gconstant {
    ///////////////////////////////////////////////////////////////////////////
    //           The values are used in the C JNI header file.               //
    //      DO NOT CHANGE THE VALUES UNLESS YOU KNOW WHAT YOU DO !!!         //
    ///////////////////////////////////////////////////////////////////////////

    final private static int JH5G_DATASET = 10 ;
    final private static int JH5G_GROUP = 20 ;
    final private static int JH5G_LINK = 30 ;
    final private static int JH5G_LINK_ERROR = 40 ;
    final private static int JH5G_LINK_HARD = 50 ;
    final private static int JH5G_LINK_SOFT = 60 ;
    final private static int JH5G_NLIBTYPES = 70 ;
    final private static int JH5G_NTYPES = 80 ;
    final private static int JH5G_NUSERTYPES = 90 ;
    final private static int JH5G_RESERVED_4 = 100 ;
    final private static int JH5G_RESERVED_5 = 110 ;
    final private static int JH5G_RESERVED_6 = 120 ;
    final private static int JH5G_RESERVED_7 = 130 ;
    final private static int JH5G_SAME_LOC = 140 ;
    final private static int JH5G_TYPE = 150 ;
    final private static int JH5G_UNKNOWN = 160 ;
    final private static int JH5G_USERTYPE = 170 ;


    ///////////////////////////////////////////////////////////////////////////
    //                Get the HDF5 constants from the library                //
    ///////////////////////////////////////////////////////////////////////////
    final public static int H5G_DATASET = J2C( JH5G_DATASET );
    final public static int H5G_GROUP = J2C( JH5G_GROUP );
    final public static int H5G_LINK = J2C( JH5G_LINK );
    final public static int H5G_LINK_ERROR = J2C( JH5G_LINK_ERROR );
    final public static int H5G_LINK_HARD = J2C( JH5G_LINK_HARD );
    final public static int H5G_LINK_SOFT = J2C( JH5G_LINK_SOFT );
    final public static int H5G_NLIBTYPES = J2C( JH5G_NLIBTYPES );
    final public static int H5G_NTYPES = J2C( JH5G_NTYPES );
    final public static int H5G_NUSERTYPES = J2C( JH5G_NUSERTYPES );
    final public static int H5G_RESERVED_4 = J2C( JH5G_RESERVED_4 );
    final public static int H5G_RESERVED_5 = J2C( JH5G_RESERVED_5 );
    final public static int H5G_RESERVED_6 = J2C( JH5G_RESERVED_6 );
    final public static int H5G_RESERVED_7 = J2C( JH5G_RESERVED_7 );
    final public static int H5G_SAME_LOC = J2C( JH5G_SAME_LOC );
    final public static int H5G_TYPE = J2C( JH5G_TYPE );
    final public static int H5G_UNKNOWN = J2C( JH5G_UNKNOWN );
    final public static int H5G_USERTYPE = J2C( JH5G_USERTYPE );

    /**
     *  J2C converts a Java constant to an HDF5 constant determined at runtime
     *
     *  @param java_constant IN: The value of Java constant
     *  
     *  @return the value of an HDF5 constant determined at runtime
     **/
    private  synchronized static native int J2C(int java_constant);}
