/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;

import hdf.h5.H5;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
///////////////////////////////////////////////////////////////////////////
//           This list must be identical to H5Constants.h                //
//                DO NOT EDIT THE LIST !!!                               //
///////////////////////////////////////////////////////////////////////////

public class H5Rconstant {
  final private static int JH5R_BADTYPE = 2950;
  final private static int JH5R_DATASET_REGION = 2960;
  final private static int JH5R_INTERNAL = 2970;
  final private static int JH5R_MAXTYPE = 2980;
  final private static int JH5R_OBJ_REF_BUF_SIZE = 2990;
  final private static int JH5R_OBJECT = 3000;

  ///////////////////////////////////////////////////////////////////////////
  //                Get the HDF5 constants from the library                //
  ///////////////////////////////////////////////////////////////////////////
  final public static int H5R_BADTYPE = H5.J2C( JH5R_BADTYPE );
  final public static int H5R_DATASET_REGION = H5.J2C( JH5R_DATASET_REGION );
  final public static int H5R_INTERNAL = H5.J2C( JH5R_INTERNAL );
  final public static int H5R_MAXTYPE = H5.J2C( JH5R_MAXTYPE );
  final public static int H5R_OBJ_REF_BUF_SIZE = H5.J2C( JH5R_OBJ_REF_BUF_SIZE );
  final public static int H5R_OBJECT = H5.J2C( JH5R_OBJECT );

  /**
   * Get the value of a constant variable from the library. Some of the
   * library constants are defined at run-time. Using get() will make sure
   * the constants are correct. 
   */
  private synchronized static native int get(String constantName);
  
}
