/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF Java Products. The full HDF Java copyright       *
 * notice, including terms governing use, modification, and redistribution,  *
 * is contained in the file, COPYING.  COPYING can be found at the root of   *
 * the source code distribution tree. You can also access it online  at      *
 * http://www.hdfgroup.org/products/licenses.html.  If you do not have       *
 * access to the file, you may request a copy from help@hdfgroup.org.        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

package hdf.h5.constants;


/**
/**
 *  This class contains C constants and enumerated types of HDF5 library.
 *  The values of these constants are obtained from the library by calling
 *  J2C(int jconstant), where jconstant is any of the private constants which
 *  start their name with "JH5" need to be converted.
 *  <p>
 *  <b>Do not edit this file!</b>
 *  </p>
 */
public class H5Rconstant {
    ///////////////////////////////////////////////////////////////////////////
    //           The values are used in the C JNI header file.               //
    //      DO NOT CHANGE THE VALUES UNLESS YOU KNOW WHAT YOU DO !!!         //
    ///////////////////////////////////////////////////////////////////////////

    final private static int JH5R_BADTYPE = 10;
    final private static int JH5R_DATASET_REGION = 20;
    final private static int JH5R_INTERNAL = 30;
    final private static int JH5R_MAXTYPE = 40;
    final private static int JH5R_OBJ_REF_BUF_SIZE = 50;
    final private static int JH5R_OBJECT = 60;

    ///////////////////////////////////////////////////////////////////////////
    //                Get the HDF5 constants from the library                //
    ///////////////////////////////////////////////////////////////////////////
    final public static int H5R_BADTYPE = J2C( JH5R_BADTYPE );
    final public static int H5R_DATASET_REGION = J2C( JH5R_DATASET_REGION );
    final public static int H5R_INTERNAL = J2C( JH5R_INTERNAL );
    final public static int H5R_MAXTYPE = J2C( JH5R_MAXTYPE );
    final public static int H5R_OBJ_REF_BUF_SIZE = J2C( JH5R_OBJ_REF_BUF_SIZE );
    final public static int H5R_OBJECT = J2C( JH5R_OBJECT );

    /**
     *  J2C converts a Java constant to an HDF5 constant determined at runtime
     *
     *  @param java_constant IN: The value of Java constant
     *  
     *  @return the value of an HDF5 constant determined at runtime
     **/
    public synchronized static native int J2C(int java_constant);  
}
