/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5D */

#ifndef _Included_hdf_h5_H5D
#define _Included_hdf_h5_H5D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dcreate2
 * Signature: (ILjava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dcreate2
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dcreate_anon
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dcreate_1anon
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dopen2
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dopen2
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_space
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dget_1space
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_space_status
 * Signature: (I)Lhdf/h5/enums/H5D_SPACE_STATUS;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5D_H5Dget_1space_1status
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_type
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dget_1type
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_create_plist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dget_1create_1plist
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_access_plist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dget_1access_1plist
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_storage_size
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5D_H5Dget_1storage_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dget_offset
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5D_H5Dget_1offset
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread
 * Signature: (IIIII[BZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5DreadVL
 * Signature: (IIIII[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5DreadVL
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_short
 * Signature: (IIIII[SZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1short
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jshortArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_int
 * Signature: (IIIII[IZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1int
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_long
 * Signature: (IIIII[JZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1long
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlongArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_float
 * Signature: (IIIII[FZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1float
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jfloatArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_double
 * Signature: (IIIII[DZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1double
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdoubleArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_string
 * Signature: (IIIII[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1string
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dread_reg_ref
 * Signature: (IIIII[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dread_1reg_1ref
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5DwriteString
 * Signature: (IIIII[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5DwriteString
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dwrite
 * Signature: (IIIII[BZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dwrite
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dwrite_short
 * Signature: (IIIII[SZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dwrite_1short
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jshortArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dwrite_int
 * Signature: (IIIII[IZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dwrite_1int
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dwrite_long
 * Signature: (IIIII[JZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dwrite_1long
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlongArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dwrite_float
 * Signature: (IIIII[FZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dwrite_1float
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jfloatArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dwrite_double
 * Signature: (IIIII[DZ)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dwrite_1double
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdoubleArray, jboolean);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dvlen_reclaim
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dvlen_1reclaim
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dvlen_get_buf_size
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5D_H5Dvlen_1get_1buf_1size
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dfill
 * Signature: ([BI[BII)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dfill
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dset_extent
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5D_H5Dset_1extent
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Ddebug
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Ddebug
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dcreate1
 * Signature: (ILjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dcreate1
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint);

/*
 * Class:     hdf_h5_H5D
 * Method:    H5Dopen1
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5D_H5Dopen1
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
