/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5F */

#ifndef _Included_hdf_h5_H5F
#define _Included_hdf_h5_H5F
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fis_hdf5
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5F_H5Fis_1hdf5
  (JNIEnv *, jclass, jstring);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fcreate
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5F_H5Fcreate
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fopen
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5F_H5Fopen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Freopen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5F_H5Freopen
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fflush
 * Signature: (ILhdf/h5/enums/H5F_SCOPE;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5F_H5Fflush
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5F_H5Fclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_create_plist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5F_H5Fget_1create_1plist
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_access_plist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5F_H5Fget_1access_1plist
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_intent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5F_H5Fget_1intent
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_obj_count
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5F_H5Fget_1obj_1count
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_obj_ids
 * Signature: (IIJ[I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5F_H5Fget_1obj_1ids
  (JNIEnv *, jclass, jint, jint, jlong, jintArray);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fmount
 * Signature: (ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5F_H5Fmount
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Funmount
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5F_H5Funmount
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_freespace
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5F_H5Fget_1freespace
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_filesize
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5F_H5Fget_1filesize
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_mdc_hit_rate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_hdf_h5_H5F_H5Fget_1mdc_1hit_1rate
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_mdc_size
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5F_H5Fget_1mdc_1size
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Freset_mdc_hit_rate_stats
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5F_H5Freset_1mdc_1hit_1rate_1stats
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5F
 * Method:    H5Fget_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5F_H5Fget_1name
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
