/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5G */

#ifndef _Included_hdf_h5_H5G
#define _Included_hdf_h5_H5G
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gcreate2
 * Signature: (ILjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5G_H5Gcreate2
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gcreate_anon
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5G_H5Gcreate_1anon
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gopen2
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5G_H5Gopen2
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gget_create_plist
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5G_H5Gget_1create_1plist
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gget_info
 * Signature: (I)Lhdf/h5/structs/H5G_info_t;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5G_H5Gget_1info
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gget_info_by_name
 * Signature: (ILjava/lang/String;I)Lhdf/h5/structs/H5G_info_t;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5G_H5Gget_1info_1by_1name
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gget_info_by_idx
 * Signature: (ILjava/lang/String;Lhdf/h5/enums/H5_INDEX;Lhdf/h5/enums/H5_ITER;JI)Lhdf/h5/structs/H5G_info_t;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5G_H5Gget_1info_1by_1idx
  (JNIEnv *, jclass, jint, jstring, jobject, jobject, jlong, jint);

/*
 * Class:     hdf_h5_H5G
 * Method:    H5Gclose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5G_H5Gclose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
