/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_constants_H5Gconstant */

#ifndef _Included_hdf_h5_constants_H5Gconstant
#define _Included_hdf_h5_constants_H5Gconstant
#ifdef __cplusplus
extern "C" {
#endif
#undef hdf_h5_constants_H5Gconstant_JH5G_DATASET
#define hdf_h5_constants_H5Gconstant_JH5G_DATASET 10L
#undef hdf_h5_constants_H5Gconstant_JH5G_GROUP
#define hdf_h5_constants_H5Gconstant_JH5G_GROUP 20L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK
#define hdf_h5_constants_H5Gconstant_JH5G_LINK 30L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK_ERROR
#define hdf_h5_constants_H5Gconstant_JH5G_LINK_ERROR 40L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK_HARD
#define hdf_h5_constants_H5Gconstant_JH5G_LINK_HARD 50L
#undef hdf_h5_constants_H5Gconstant_JH5G_LINK_SOFT
#define hdf_h5_constants_H5Gconstant_JH5G_LINK_SOFT 60L
#undef hdf_h5_constants_H5Gconstant_JH5G_NLIBTYPES
#define hdf_h5_constants_H5Gconstant_JH5G_NLIBTYPES 70L
#undef hdf_h5_constants_H5Gconstant_JH5G_NTYPES
#define hdf_h5_constants_H5Gconstant_JH5G_NTYPES 80L
#undef hdf_h5_constants_H5Gconstant_JH5G_NUSERTYPES
#define hdf_h5_constants_H5Gconstant_JH5G_NUSERTYPES 90L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_4
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_4 100L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_5
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_5 110L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_6
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_6 120L
#undef hdf_h5_constants_H5Gconstant_JH5G_RESERVED_7
#define hdf_h5_constants_H5Gconstant_JH5G_RESERVED_7 130L
#undef hdf_h5_constants_H5Gconstant_JH5G_SAME_LOC
#define hdf_h5_constants_H5Gconstant_JH5G_SAME_LOC 140L
#undef hdf_h5_constants_H5Gconstant_JH5G_TYPE
#define hdf_h5_constants_H5Gconstant_JH5G_TYPE 150L
#undef hdf_h5_constants_H5Gconstant_JH5G_UNKNOWN
#define hdf_h5_constants_H5Gconstant_JH5G_UNKNOWN 160L
#undef hdf_h5_constants_H5Gconstant_JH5G_USERTYPE
#define hdf_h5_constants_H5Gconstant_JH5G_USERTYPE 170L
/*
 * Class:     hdf_h5_constants_H5Gconstant
 * Method:    J2C
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_constants_H5Gconstant_J2C
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
