/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5I */

#ifndef _Included_hdf_h5_H5I
#define _Included_hdf_h5_H5I
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iregister
 * Signature: (Lhdf/h5/enums/H5I_TYPE;[B)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iregister
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iobject_verify
 * Signature: (ILhdf/h5/enums/H5I_TYPE;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5I_H5Iobject_1verify
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iremove_verify
 * Signature: (ILhdf/h5/enums/H5I_TYPE;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5I_H5Iremove_1verify
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iget_type
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iget_1type
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iget_file_id
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iget_1file_1id
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iget_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hdf_h5_H5I_H5Iget_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iinc_ref
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iinc_1ref
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Idec_ref
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Idec_1ref
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iget_ref
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iget_1ref
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iclear_type
 * Signature: (Lhdf/h5/enums/H5I_TYPE;Z)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5I_H5Iclear_1type
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Idestroy_type
 * Signature: (Lhdf/h5/enums/H5I_TYPE;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5I_H5Idestroy_1type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iinc_type_ref
 * Signature: (Lhdf/h5/enums/H5I_TYPE;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iinc_1type_1ref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Idec_type_ref
 * Signature: (Lhdf/h5/enums/H5I_TYPE;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Idec_1type_1ref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iget_type_ref
 * Signature: (Lhdf/h5/enums/H5I_TYPE;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5I_H5Iget_1type_1ref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Inmembers
 * Signature: (Lhdf/h5/enums/H5I_TYPE;)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5I_H5Inmembers
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Itype_exists
 * Signature: (Lhdf/h5/enums/H5I_TYPE;)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5I_H5Itype_1exists
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5I
 * Method:    H5Iis_valid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5I_H5Iis_1valid
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
