/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5S */

#ifndef _Included_hdf_h5_H5S
#define _Included_hdf_h5_H5S
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5S
 * Method:    H5Screate
 * Signature: (Lhdf/h5/enums/H5S_CLASS;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Screate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Screate_simple
 * Signature: (I[J[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Screate_1simple
  (JNIEnv *, jclass, jint, jlongArray, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sset_extent_simple
 * Signature: (II[J[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Sset_1extent_1simple
  (JNIEnv *, jclass, jint, jint, jlongArray, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Scopy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Scopy
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sencode
 * Signature: (I[B[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Sencode__I_3B_3J
  (JNIEnv *, jclass, jint, jbyteArray, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sencode
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_hdf_h5_H5S_H5Sencode__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sdecode
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Sdecode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_simple_extent_npoints
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5S_H5Sget_1simple_1extent_1npoints
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_simple_extent_ndims
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Sget_1simple_1extent_1ndims
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_simple_extent_dims
 * Signature: (I[J[J)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5S_H5Sget_1simple_1extent_1dims
  (JNIEnv *, jclass, jint, jlongArray, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sis_simple
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5S_H5Sis_1simple
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_npoints
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5S_H5Sget_1select_1npoints
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sselect_hyperslab
 * Signature: (ILhdf/h5/enums/H5S_SELECT_OPER;[J[J[J[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sselect_1hyperslab
  (JNIEnv *, jclass, jint, jobject, jlongArray, jlongArray, jlongArray, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sselect_elements
 * Signature: (ILhdf/h5/enums/H5S_SELECT_OPER;J[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sselect_1elements
  (JNIEnv *, jclass, jint, jobject, jlong, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_simple_extent_type
 * Signature: (I)Lhdf/h5/enums/H5S_CLASS;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5S_H5Sget_1simple_1extent_1type
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sset_extent_none
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sset_1extent_1none
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sextent_copy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sextent_1copy
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sextent_equal
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5S_H5Sextent_1equal
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sselect_all
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sselect_1all
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sselect_none
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sselect_1none
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Soffset_simple
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Soffset_1simple
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sselect_valid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5S_H5Sselect_1valid
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_hyper_nblocks
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5S_H5Sget_1select_1hyper_1nblocks
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_elem_npoints
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_hdf_h5_H5S_H5Sget_1select_1elem_1npoints
  (JNIEnv *, jclass, jint);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_hyper_blocklist
 * Signature: (IJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_hdf_h5_H5S_H5Sget_1select_1hyper_1blocklist
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_elem_pointlist
 * Signature: (IJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_hdf_h5_H5S_H5Sget_1select_1elem_1pointlist
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_bounds
 * Signature: (I[J[J)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5S_H5Sget_1select_1bounds
  (JNIEnv *, jclass, jint, jlongArray, jlongArray);

/*
 * Class:     hdf_h5_H5S
 * Method:    H5Sget_select_type
 * Signature: (I)Lhdf/h5/enums/H5S_SEL;
 */
JNIEXPORT jobject JNICALL Java_hdf_h5_H5S_H5Sget_1select_1type
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
