/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdf_h5_H5Z */

#ifndef _Included_hdf_h5_H5Z
#define _Included_hdf_h5_H5Z
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdf_h5_H5Z
 * Method:    H5Zunregister
 * Signature: (Lhdf/h5/enums/H5Z_FILTER;)V
 */
JNIEXPORT void JNICALL Java_hdf_h5_H5Z_H5Zunregister
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5Z
 * Method:    H5Zfilter_avail
 * Signature: (Lhdf/h5/enums/H5Z_FILTER;)Z
 */
JNIEXPORT jboolean JNICALL Java_hdf_h5_H5Z_H5Zfilter_1avail
  (JNIEnv *, jclass, jobject);

/*
 * Class:     hdf_h5_H5Z
 * Method:    H5Zget_filter_info
 * Signature: (Lhdf/h5/enums/H5Z_FILTER;)I
 */
JNIEXPORT jint JNICALL Java_hdf_h5_H5Z_H5Zget_1filter_1info
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
